packages/vaex-astro/vaex/astro/transformations.py

Added galactic (l,b) to equatorial  (ra, dec) coordinate transformations.

Added coordinate transformations: galactic to equatorial.

---

packages/vaex-core/vaex/dataset.py
packages/vaex-core/vaex/test/dataset.py

Added two new selection methods: one for circular and one for elliptical regions.

new: added ds.select_circle/ellipse

---

packages/vaex-astro/vaex/astro/transformations.py
tests/virtual_columns_test.py

Adding a virtual column method that computes the angular momentum components given Cartesian positions and velocities.  The method is accompanies by an unit-test that passes.

Angular momentum

---

packages/vaex-core/vaex/dataset.py
tests/dropna_test.py

Added unit-tests for `dropna`. Also checking how `dropna` behaves for columns of `dtype` "object".

Added a new unittests for dropna.

---

packages/vaex-core/vaex/dataset.py
tests/cast_to_array_test.py
tests/drop_test.py
tests/getattr_test.py

Small typo but may be breaking other code.

Fix for shallow copies with 'missing' columns, and tests and fixes for dataset.__array__()

---

packages/vaex-core/vaex/dataset.py
tests/copy_test.py
tests/getattr_test.py
tests/state_test.py
tests/virtual_columns_test.py

Adding a unit-test that check the access to a `DatasetArray` object after virtual columns have been added to a `Dataset`. At the moment the tests expose a potential issue.

Testing accessing DatasetArrays after defining virtual columns. 

---

packages/vaex-core/vaex/utils.py
tests/json_export_test.py

Created a NumpyEncoder class to help with encoding json

NumpyEncoder for json write

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/tasks.py
tests/category_test.py

This is a start for value_counts, only works/tested for 'integer' data. 
TODO:

value_counts support

---

packages/vaex-core/vaex/dataframe.py

new: str(df) and repr(df) give a readable printout of a table

---

packages/vaex-core/vaex/expression.py
tests/apply_test.py

When run apply on an Expression, it run it through the dataframe

apply on an expression

---

.travis.yml
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/expresso.py
tests/graph_test.py

This can be used to gain insight into the virtual expression, but its main usecase now is to be able to run refit for vaex-ml
Example:

New: experimental expression graph access methods

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py

Allows very long dataframes
see https://twitter.com/maartenbreddels/status/1101416485241671685
(needs rebase)

Allow googol length dataframes

---

packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
tests/datetime_test.py

Adding additional `datetime` operations. Each operation is covered by a unit-test.

Adding additional datetime operations, and improving test coverage.

---

packages/vaex-viz/vaex/viz/mpl.py

Small fix, so `return_extra` in the `plot` method can work.

Removed unused, undefined variable in the `plot` method.

---

packages/vaex-core/vaex/dataframe.py

Fixes some errors in the API docs.

Update to the API docs.

---

.travis.yml
appveyor.yml
packages/vaex-core/setup.py
packages/vaex-core/src/strings.cpp

PCRE is much faster than the other regex libraries, we now get a 10x versus 2-4x speed improvement compared to Python's regex library.
Also contains performance increases for releasing the GIL (>x10).

Superstrings take3: use PCRE for regular expressions + performance tweaks

---

packages/vaex-core/src/strings.cpp

This allows us to build binary wheels.

Use xpressive so we can support regex-broken gcc4.8 / manylinux

---

packages/vaex-arrow/vaex_arrow/convert.py
tests/common.py
tests/export_test.py

The added unit-tests exposes an issue when saving a `dataframe` which has a boolean column to the `arrow` format.

Adding unit-tests to improve exporting of data to local storage.

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/file/other.py
packages/vaex-core/vaex/legacy.py
packages/vaex-core/vaex/remote.py
packages/vaex-core/vaex/test/dataset.py
packages/vaex-hdf5/vaex/hdf5/dataset.py
tests/category_test.py

fix deprecation issues

---

packages/vaex-core/vaex/dataframe.py
tests/drop_test.py

Fix autocomplete

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/functions.py
tests/common.py
tests/datetime_test.py

Bug is fixed in pandas, we have to live with it for a while
https://github.com/pandas-dev/pandas/pull/21688

fix: pandas has issues with read only buffers, this is a workaround

---

packages/vaex-core/src/strings.cpp
packages/vaex-core/src/superstring.hpp
packages/vaex-core/vaex/column.py
tests/internal/strings_module_test.py

Wasn't using the header file which could lead to mismatches in the vtables of the c++ objects. Included some cleanups with it.

cleanups for strings, use header file for StringSequence

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
tests/expression_variables_test.py
tests/getattr_test.py

This fixes issues like this:
This should replace #244

Fix: virtual columns depending on virtual columns were not properly copied

---

packages/vaex-jupyter/vaex/jupyter/bqplot.py
packages/vaex-jupyter/vaex/jupyter/plot.py
tests/jupyter/plot_widget_test.py

The test for now just does coverage

fix and test plot_widget with float32 and minmax limits, solves #243

---

.travis.yml
appveyor.yml
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataset_mmap.py
packages/vaex-core/vaex/file/__init__.py
packages/vaex-core/vaex/file/cache.py
packages/vaex-core/vaex/file/column.py
packages/vaex-core/vaex/file/s3.py
packages/vaex-core/vaex/utils.py
packages/vaex-hdf5/vaex/hdf5/dataset.py
requirements.txt
tests/internal/filecache_test.py
tests/s3_test.py

(file.open now also takes a list)
Closes:  #258
This supports hdf5 file loading from s3, using a local cache (default is 1mb chunks). It seems there is still a bit of overhead, it is not as performant yet as a local file, even when everything is cached.
Note that when everything that is required is in cache, no request will be make to s3.

feat(core,hdf5): support for loading and caching from s3

---

packages/vaex-core/vaex/dataframe.py
tests/sort_test.py

Adding a unit-test which tests the sorting of a filtered DataFrame, which currently exposes a bug.

Adding a test for sorting a filtered DataFrame

---

packages/vaex-core/vaex/dataframe.py
tests/slice_test.py

fix(core): slicing beyond the end of a dataframe should clip it

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
tests/slice_test.py

See https://github.com/vaexio/vaex/issues/238

feat(core,expression): allow slicing of expressions

---

packages/vaex-core/src/superagg.cpp
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/dataframe.py
tests/groupby_test.py

Added unit-tests for
- standard deviation aggregator for numeric types;
- mode (most common value) for string/object type.

Unit-tests for additional groupby aggregators

---

packages/vaex-core/vaex/utils.py
tests/datetime_test.py

This is a redo of the screwup in #305

Timedelta min max fix

---

packages/vaex-core/src/superagg.cpp
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/dataframe.py
tests/groupby_test.py

This is a redo of #255 after the screwup in #305

Groupby update

---

packages/vaex-core/vaex/agg.py
tests/groupby_test.py

fix(core,std): standard deviation upcasts numbers to float64 for accuracy

---

packages/vaex-core/vaex/file/cache.py

this was causing "OSErro:r Cannot allocate memory"

fix(core): using s3 cache, mmap was called too often via .dup()

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/geo.py

that include all geometry/geographic functions previously in the DataFrame.
This cleans up the DataFrame API quite a lot.

feat(geo): have a geo accessor

---

tests/cast_to_array_test.py

see https://github.com/pytest-dev/pytest/issues/3974
or https://docs.pytest.org/en/4.6-maintenance/deprecations.html#message-parameter-of-pytest-raises

fix(test): pytest decided to break pytest.raises

---

packages/vaex-core/src/strings.cpp
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
tests/strings_test.py

feat(core,strings): support for == and + operators for strings

---

tests/ml/ml_test.py

The `LabelEncoder` (`vaex-ml`) test is improved to remove the inherent flakiness due to the randomness with which the data was generated. 
The data now is fixed, and thus we have much better control over the test results. Everything is tested much in the same way as before.

Improved test for LabelEncoder (vaex-ml)

---

packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/selections.py
packages/vaex-ml/vaex/ml/transformations.py
tests/dropna_test.py
tests/fillna_test.py
tests/value_counts_test.py

A couple of unit-tests that check the consistency of how the missing values are handled through several methods (`value_counts`, `fillna`, `isna`)

Unit-tests for checking the consistency between handling of missing values

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/remote.py
packages/vaex-jupyter/setup.py
packages/vaex-jupyter/vaex/jupyter/__init__.py
packages/vaex-jupyter/vaex/jupyter/bqplot.py
packages/vaex-jupyter/vaex/jupyter/create.py
packages/vaex-jupyter/vaex/jupyter/grid.py
packages/vaex-jupyter/vaex/jupyter/plot.py
packages/vaex-jupyter/vaex/jupyter/state.py
packages/vaex-jupyter/vaex/jupyter/viz.py
packages/vaex-jupyter/vaex/jupyter/widgets.py
requirements.txt
tests/jupyter/plot_widget_test.py
tests/jupyter/widget_core_test.py

Using ipyvuetify we can now build much richer interfaces:

refactor+feat(jupyter): redo interface with ipyvuetify

---

packages/vaex-core/src/hash_primitives.cpp
packages/vaex-core/src/hash_string.cpp
packages/vaex-core/vaex/hash.py
packages/vaex-core/vaex/json.py
tests/json_export_test.py
tests/map_test.py

to allow map() to be used for state transfer

fix(core): implement serialization of ordered_map

---

packages/vaex-core/vaex/dataframe.py

Introduced in 65e634c318a23d655dd28125386c4fe75b9df1c6

fix(core): df.sort and df.take had a bug, that sometimes cancelled.

---

packages/vaex-arrow/vaex_arrow/convert.py
packages/vaex-core/vaex/column.py
tests/export_test.py

Closes https://github.com/vaexio/vaex-talks/issues/1

fix(arrow/parquet): support for empty strings

---

packages/vaex-core/vaex/functions.py

fix(core,dt): Pandas 0.25 does not accept read only for dt accessor

---

packages/vaex-core/src/hash_primitives.cpp
packages/vaex-core/src/hash_string.cpp
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/hash.py
tests/internal/hash_test.py
tests/join_test.py

Joining is now using the same hash table structures. Benchmarks should follow soon.

Superjoin: join now uses the new hash tables

---

packages/vaex-core/vaex/dataframe.py
tests/join_test.py

fix(core,join): inplace was not respected fow how=right

---

packages/vaex-core/vaex/dataframe.py
tests/join_test.py

Adding an additional unit-test for `join`, which is exposing an issue.

Join: adding additional unit-test

---

packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
tests/join_test.py

fix(core,join): when doing join after join, we avoid two levels of indirection

---

packages/vaex-core/vaex/remote.py
packages/vaex-core/vaex/webserver.py

Forwarding methods to the server is now implemented using a decorator, this could clean up the rest of the code as well.

perf: forward _head_and_tail_table to server for better performance

---

packages/vaex-hdf5/vaex/hdf5/dataset.py
tests/column_names_test.py

feat(hdf5): read hdf5 files with invalid column names

---

packages/vaex-core/vaex/dataframe.py
tests/astype_test.py
tests/rename_test.py

This is a unit-test exposing the issue #395.

(core, test) Testing dtype of columns when astype and str methods are used together.

---

packages/vaex-core/vaex/dataframe.py
tests/join_test.py

A unit-test that exposes a an issue with inner join when the left DataFrame is filtered. 
It looks like when doing inner join, the filter(s) are being ignored.

Unit-test for inner join with filtered DataFrames.

---

packages/vaex-core/vaex/column.py
tests/join_test.py

fix(core): do not check max_index is the ColumnIndex refers to nothing

---

packages/vaex-arrow/vaex_arrow/dataset.py

feat(arrow): support arrow DictionaryType

---

packages/vaex-arrow/vaex_arrow/dataset.py
tests/arrow/stream_file_test.py

Feat arrow file and stream

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-jupyter/vaex/jupyter/utils.py
packages/vaex-ui/vaex/ui/layers.py

This is useful if you only want to redraw when you display a particular selection.

feat(jupyter): pass selection name to the selection_changed event

---

.travis.yml

I hope this fixes the osx py36 failure

core(ci): install certifi with conda, since pip cannot do it

---

packages/vaex-core/src/superagg.cpp
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/utils.py
tests/agg_test.py

fix: upcast dtype of sum aggregators to avoid overflow

---

.travis.yml
appveyor.yml
packages/vaex-graphql/vaex/graphql/__init__.py
packages/vaex-graphql/vaex/graphql/tornado.py
setup.py
tests/graphql_test.py

feat(graphql): add where clause to have hasura like filtering, and row api

---

packages/vaex-core/src/strings.cpp
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
tests/isin_test.py

This PR implements the `isin()` method. 
The test is done following the expected results form `pandas`.  Important to note the `np.nan`, and the `None` behaviour. 
Related to #375

Feat: add isin() method

---

packages/vaex-core/vaex/dataframe.py
tests/sort_test.py

Enable multi-key sorting of a DataFrame

---

packages/vaex-core/vaex/multithreading.py
packages/vaex-core/vaex/scopes.py

This makes debugging much better in combination with pdb, before it would get this internal errors and meaningless stack traces.

Fix pytest debugging

---

packages/vaex-ml/vaex/ml/catboost.py
tests/ml/catboost_test.py
tests/ml/lightgbm_test.py
tests/ml/xgboost_test.py

Improve outdated tests for xgboost, catboost and lightgbm

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/execution.py

Mostly relevant for developing

refactor: avoid complicated stack traces by catching exceptions earlier

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/legacy.py
packages/vaex-core/vaex/tasks.py
packages/vaex-core/vaex/test/dataset.py
tests/evaluate_test.py

This PR handles the case of evaluating a virtual column coming from a custom functino on a filtered DataFrame.

Apply filter before applying function

---

packages/vaex-core/vaex/dataframe.py
tests/fillna_test.py

Fix fillna when applied to the whole dataframe

---

CHANGELOG.md
packages/vaex-core/vaex/core/_version.py
packages/vaex-meta/setup.py
packages/vaex-meta/vaex/meta/_version.py
packages/vaex-ml/vaex/ml/_version.py

We forgot to update the changelog and versions, this is correcting that. We may want to have CI check that we do that.

chore: update changelog and versions

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/tasks.py
tests/agg_test.py

Follow up of #483 to also filter in the aggregators.

Feat pre filter aggregators

---

docs/source/example_ml_iris.ipynb
docs/source/example_ml_titanic.ipynb

Small fixes to ML docks: heading and typos.

Small fixes to ML docs

---

CHANGELOG.md
packages/vaex-astro/vaex/astro/transformations.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/geo.py
packages/vaex-core/vaex/test/dataset.py
tests/conftest.py
tests/expression_variables_test.py
tests/join_test.py
tests/rename_test.py
tests/variables_test.py

Various fixes (and breaking changes) coming out of #415

Refactor variables

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
tests/repr_test.py

fix: print empty dataframes

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expresso.py
tests/copy_test.py
tests/getattr_test.py

fix(core): give a better error msg on copying a dataframe with non-existing column

---

packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
tests/common.py
tests/concat_test.py

We not run all test also on the concatenated dataframe, and added some extra test.
Also, we now support filtered dataframe to be concatenated.

Fixes/features for concat / concatenate 

---

CHANGELOG.md
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
tests/sparse_test.py

fix: copy sparse matrices

---

.github/workflows/pythonpackage.yml
.travis.yml
appveyor.yml
requirements-ml.txt

Improve the CI by enabling the testing of vaex.ml in github actions, and making a more uniform requirements-ml file.

chore: reformat dependencies in CI config files

---

README.rst
packages/vaex-meta/README.rst

Fix ML link in readme

---

CHANGELOG.md
packages/vaex-core/vaex/functions.py
tests/isin_test.py

Test for the issue exposed by #631

`df.isin` fix for dtype object

---

packages/vaex-core/vaex/expresso.py
tests/expresso_test.py

This also includes yet uncommitted tests for the expresso module.

fix(expresso): support floor div, fixes #634

---

packages/vaex-ui/vaex/ui/main.py

DatasetRemote <-- DataFrameRemote
Seems to make the UI work again

Debugging UI: renamed class not propagated

---

packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
tests/concat_test.py

Fixes #661 and solves an issue found in https://github.com/vaexio/vaex/pull/678

fix(core): for concatenated column we did not always determine the fill value

---

packages/vaex-core/src/hash_object.cpp
packages/vaex-core/src/superagg.cpp

As mentioned here: https://github.com/vaexio/vaex/issues/606#issuecomment-590407455
this should fix compilation with gcc5, this was still in my git stash. (cc @nugend )

chore(core): fix compilation issue with gcc5

---

.github/workflows/pythonpackage.yml
.travis.yml
appveyor.yml
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/groupby.py
tests/groupby_test.py

Replaces #345, should run the benchmarks on asv because of the branch name

Performance: groupby faster due to category and reusing count(*) 🔥

---

tests/jupyter/async_test.py

Should fix the failure seen in https://travis-ci.org/github/vaexio/vaex/jobs/686009118

test: fix async test, was missing await

---

.github/workflows/pythonpackage.yml
.travis.yml
appveyor.yml
packages/vaex-core/setup.py

Yet another PR to fix the CI. Currently xgboost is giving trouble on mac.
Addresses #748

Fix for the CI

---

CHANGELOG.md
docs/source/tutorial.ipynb
packages/vaex-core/vaex/dataframe.py
tests/agg_test.py
tests/category_test.py
tests/groupby_test.py
tests/jupyter/model_test.py
tests/jupyter/plot_widget_test.py
tests/ml/linear_model_test.py

I think this is the last v3 breaking change we needed to do.

refactor!: df.categorize takes an inplace=False argument

---

packages/vaex-core/vaex/__init__.py
packages/vaex-server/vaex/server/client.py
packages/vaex-server/vaex/server/tornado_client.py

Some minor last fixes/changes.

Fix server check and port and allows vaex+ws scheme

---

README.md
binder/requirements.txt
packages/vaex-meta/README.md

chore: update README with links to articles

---

packages/vaex-core/vaex/__init__.py

Closes https://github.com/vaexio/vaex/issues/776
Closes https://github.com/vaexio/vaex/issues/766

fix: support from_pandas_df with pandas 0.23

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/functions.py

This PR adds `df.dropinf()`, i.e. dropping rows with infinities from the dataframe. 
Looks like this:

Feature: df.dropinf() implementation

---

docs/source/faq.ipynb

Updating the FAQ section of the docs.
It now addresses the question posted by #837

Docs: Update the FAQ

---

packages/vaex-core/vaex/expresso.py
tests/expresso_test.py

fix: expression containing kwarg=True were treated as invalid

---

packages/vaex-ml/vaex/ml/linear_model.py
packages/vaex-ml/vaex/ml/transformations.py

We performed some code refactoring. This refactoring can result in more readable and non-duplicate code.
Thanks!

Some Refactoring

---

packages/vaex-ml/vaex/ml/ui.py

I improved the quality of the code by eliminating duplication. Thank you.

Refactoring: Deduplication

---

packages/vaex-ml/vaex/ml/cluster.py

I think True is more intuitive than 1 when executing conditional statement unconditionally.
Thank You!

Refactoring: if 1 -> if True

---

.github/workflows/pythonpackage.yml
tests/jupyter/model_test.py

The async tests didnt run on GHA, because we did not have pytest-asyncio installed.

Chore: fix ci async

---

.github/workflows/pythonpackage.yml
appveyor.yml
ci/conda-env.yml
packages/vaex-core/vaex/functions.py
tests/ml/catboost_test.py
tests/ml/xgboost_test.py

Adding a couple of additional numpy functions.

Feat additional numpy functions

---

CHANGELOG.md
ci/05-run-notebooks.sh
packages/vaex-astro/setup.py
packages/vaex-astro/vaex/astro/_version.py
packages/vaex-graphql/setup.py
packages/vaex-graphql/vaex/graphql/_version.py
packages/vaex-jupyter/setup.py
packages/vaex-jupyter/vaex/jupyter/_version.py
packages/vaex-meta/setup.py
packages/vaex-meta/vaex/meta/_version.py
packages/vaex-ml/setup.py
packages/vaex-server/setup.py
packages/vaex-server/vaex/server/_version.py
packages/vaex-viz/setup.py
packages/vaex-viz/vaex/viz/_version.py
setup.py

the pip install should fail because vaex-ml has wrong pinned dependencies.

chore: a failing install of a subpackage did not stop the installation

---

.github/workflows/pythonpackage.yml
packages/vaex-core/vaex/dataset.py

This will run the test suite of the Python packages of vaex-enterprise as part of the vaex CI. This will increase test coverage and will detect breaking changes.

chore: install/test vaex-enterprise

---

packages/vaex-core/vaex/dataframe.py

The setter is responsible for clearing caches etc.
This makes it much safer to assign to dataset.

chore(core): make df.dataset a property with setter

---

CHANGELOG.md
packages/vaex-core/vaex/arrow/dataset.py

Note, this is a breaking change.

feat(core)!: opening arrow files will now expose them as arrow arrays

---

CHANGELOG.md
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py

Performance can still be improved, but this was an easy fix, and makes it usable.
Closes #604 
Closes #812 
Closes #788

perf(core): df.concat was slow, over 100x faster

---

benchmarks/bookkeeping.py
docs/source/api.rst
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/arrow/dataset.py
packages/vaex-core/vaex/arrow/numpy_dispatch.py
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/dataset.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/schema.py
packages/vaex-core/vaex/selections.py
packages/vaex-core/vaex/test/dataset.py
packages/vaex-hdf5/vaex/hdf5/export.py
packages/vaex-ml/vaex/ml/transformations.py
tests/arrow/dataset_test.py
tests/common.py
tests/concat_test.py
tests/dataset_test.py
tests/export_test.py
tests/expression_variables_test.py
tests/fillna_test.py
tests/from_dict_test.py
tests/json_export_test.py
tests/ml/ml_test.py
tests/strings_test.py

test(core): df.concat should allow mismatched schemas and null types

---

packages/vaex-core/vaex/arrow/dataset.py

fix: too large parquet files are split in rowgroups

---

packages/vaex-core/vaex/arrow/dataset.py
packages/vaex-core/vaex/dataframe.py
tests/arrow/io_test.py

Fixes #786
r? @maartenbreddels

Fix opening of Arrow non-stream files

---

.github/workflows/pythonpackage.yml
appveyor.yml
ci/conda-env.yml
packages/vaex-core/setup.py
packages/vaex-core/src/superagg.cpp
packages/vaex-core/src/superagg_binners.cpp

TODO: get py38 on linux working by splitting cpp file (probably a compiler memory usage issue)

Chore ci optimize

---

packages/vaex-core/vaex/arrow/numpy_dispatch.py
tests/compute_test.py

Fixes #1076 
Cleaning up the code fixed this, also well tested now.

fix: mixing string and numerical comparisons would expose NumpyDispatch

---

docs/source/tutorial.ipynb
packages/vaex-core/vaex/arrow/convert.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/misc/progressbar.py
packages/vaex-core/vaex/multiprocessing.py
packages/vaex-core/vaex/multithreading.py
packages/vaex-core/vaex/utils.py
tests/apply_test.py

feat: apply with multiprocessing

---

packages/vaex-core/vaex/dataset.py

fixed trivial typo in dataset.py

---

benchmarks/export.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/dataset_mmap.py
packages/vaex-core/vaex/file/column.py
packages/vaex-core/vaex/itertools.py
packages/vaex-core/vaex/utils.py
packages/vaex-hdf5/vaex/hdf5/dataset.py
packages/vaex-hdf5/vaex/hdf5/utils.py
packages/vaex-hdf5/vaex/hdf5/writer.py
tests/export_test.py

We left the old code in place, but the new code is much easier to work
with, and is about 3-5x faster in some cases, and with many virtual
columns should be much faster.

refactor(hdf5): we now evaluate and write all columns in parallel

---

packages/vaex-core/vaex/scopes.py

Fixed #1111
Otherwise NumPy can do things elementwise.
Note that variables are not wrapped, otherwise it's a bit hard to use
when variables are used in lists (which are not inspected).
On the long term we may want to rewrite the AST to use functions, instead
of overriding the `__mul__` operators etc.

fix: wrap arrays returned from the selection scope

---

packages/vaex-core/vaex/functions.py
tests/astype_test.py
tests/datetime_test.py
tests/open_test.py

Fixes #1118 alternative to #1125 closes #1125

fix: astype (or casting) for arrow types work better

---

packages/vaex-core/vaex/hash.py
tests/pickle_test.py

ordered set cannot be pickled

---

packages/vaex-core/vaex/convert.py
tests/open_test.py

fix: open with convert with non-hdf5 target still wrote to hdf5

---

packages/vaex-core/vaex/column.py
tests/column_test.py

Fixes #1188

---

packages/vaex-core/vaex/arrow/utils.py
packages/vaex-core/vaex/functions.py
tests/strings_test.py

Now we can do arbitrarily nested lists of string using split, and going back with str.join, and all string operations work on them.

feat: more string list support

---

packages/vaex-core/src/strings.cpp
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/functions.py
tests/internal/strings_module_test.py

fix: bind lifetime of string data to c++ object

---

packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/utils.py
tests/limits_test.py

doing some benchmarking and tracing on small amounts of data, this can reduce execution time from ~80msec to ~50msec.

Perf: small data

---

packages/vaex-core/vaex/dataframe.py

Add optional keywords to df.state_load to match df.state_set

---

packages/vaex-ml/vaex/ml/spec.json
packages/vaex-ml/vaex/ml/transformations.py

Just makes things look prettier.

Allow use of widget progress bar in PCA

---

packages/vaex-core/vaex/scopes.py
tests/dropna_test.py

This addresses the problem reported by #1013 
Checklist:

test(core): test for dropna when column names as numbers

---

docs/source/example_io.ipynb

Fixes a typo in I/O Kung-Fu docs.

Fix typo in I/O Kung-Fu docs

---

packages/vaex-core/vaex/dataframe.py
tests/state_test.py

This exposes unwanted behavior when filtered dataframe is also sliced. See comments in the code for mode details.

State transfer fix 

---

packages/vaex-core/vaex/datatype.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/hash.py
packages/vaex-core/vaex/utils.py
tests/groupby_test.py

This PR closes #1024.
Checklist:

✨ Feature: groupby datetime support

---

packages/vaex-core/vaex/dataframe.py
tests/join_test.py

In this PR we enable joining of dataframe on datetime columns.
Feature requested in #848 .
Checklist

Feat: join on datetime columns

---

packages/vaex-core/vaex/functions.py
packages/vaex-ml/vaex/ml/transformations.py
tests/ml/ml_test.py

Adds dtype arg to dt.func.where()

---

packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
tests/strings_test.py

Adds support for the `!=` operator on string columns. Fixes #1334

Adds support for the `!=` operator on string columns; Fixes #1334

---

packages/vaex-astro/vaex/astro/fits.py

Hello, another quick fix to the FITS reader from me! Adds a few missing imports and updates leftover pre-v4.0 naming conventions.

Update imports and names in fits.py

---

packages/vaex-core/vaex/expresso.py

more context about  what exactly is "not an expression"

parse_expression: improve assert message

---

packages/vaex-core/vaex/scopes.py
tests/selection_test.py

Similar to #1377 cc @antoinerg  @nicolaskruchten

🐛 column names equal to function names in selections/filters

---

packages/vaex-core/vaex/dataset.py
tests/concat_test.py

🐛 concat with resolver=strict failed

---

docs/source/example_io.ipynb

Keeping up to date with the latest changes from https://github.com/vaexio/vaex/pull/1364

Docs: add to_records example in the io example page

---

.github/workflows/pythonpackage.yml
ci/02-create-vaex-dev-env.sh
ci/03-install-vaex.sh
ci/04-run-test-suite.sh
ci/05-run-notebooks.sh
docs/source/example_io.ipynb
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-hdf5/vaex/hdf5/dataset.py
packages/vaex-hdf5/vaex/hdf5/writer.py
tests/open_test.py

This was requested in https://github.com/vaexio/vaex/issues/1430
Checklist:

Feature: support reading and writing of groups from/to hdf5 files

---

packages/vaex-core/vaex/functions.py
tests/datetime_test.py

Add quarter and halfyear datetime methods.

---

packages/vaex-core/vaex/expression.py

A print statement was present in the map function.

remove print nan_value from map

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/cache.py
packages/vaex-core/vaex/dataset.py

This showed up a lot with plotly dash in edit mode when the app
reloads.

🐛 thread safety issues due to global caching and patching

---

.github/workflows/pythonpackage.yml
ci/conda-env-extra.yml
packages/vaex-ml/setup.py
packages/vaex-ml/vaex/ml/tensorflow.py
tests/ml/tensorflow_test.py

Few additional features for the tensorflow/keras addition to vaex-ml :

Additional features for the keras transformer

---

packages/vaex-ml/vaex/ml/tensorflow.py
tests/ml/tensorflow_test.py

Also update a test to reflect this. Also made on of the tests significantly faster.
@maartenbreddels feel free to push other fixes as you see fit!

Allow the keras model to serialize custom functions or classes

---

.github/workflows/pythonpackage.yml
benchmarks/fixtures.py
benchmarks/groupbyh2o.py

This PR adds some more benchmarks in the style of the [h2o db-benchmarks repo](https://github.com/h2oai/db-benchmark).
This is useful for tracking the performance of vaex as we continue development.

benchmarks: add groupby benchmarks in the style of the h2o repo

---

.github/workflows/pythonpackage.yml
.github/workflows/wheel.yml
ci/actions/windll/action.yml
packages/vaex-server/setup.py
packages/vaex-server/vaex/server/__main__.py
packages/vaex-server/vaex/server/fastapi.py
packages/vaex-server/vaex/server/server.py
packages/vaex-server/vaex/server/websocket.py

This does not get triggered in CI, we might want to improve that.

🐛 vaex-server was broken (missing import and untracked file)

---

packages/vaex-core/vaex/cache.py
packages/vaex-core/vaex/expression.py
tests/cache_test.py

I think we want to eventually make a decorator out of this, and support the delay=True case.cc

🐎 cache nunique

---

benchmarks/groupby.py
packages/vaex-core/src/hash.hpp
packages/vaex-core/src/superutils.cpp
tests/internal/hash_test.py

Includes a benchmark so we can track this.

🐎 groupby was slow for particular data

---

packages/vaex-core/src/hash.hpp
packages/vaex-core/src/hash_object.cpp
packages/vaex-core/src/hash_primitives.cpp
packages/vaex-core/src/hash_primitives.hpp
packages/vaex-core/src/hash_string.cpp
packages/vaex-core/src/hash_string.hpp
packages/vaex-core/vaex/cache.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/encoding.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/hash.py
packages/vaex-core/vaex/json.py
tests/fingerprint_test.py
tests/internal/hash_test.py

We now use the base df fingerprint to create a set fingerprint
that we store in the set object.

🐎 df.fingerprint will be faster due to set fingerprint speeups

---

packages/vaex-core/vaex/functions.py
tests/datetime_test.py

Fix: datetime operations on virtual columns created via astype

---

packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
tests/datetime_test.py
tests/state_test.py

This will cause the fingerprint to change, and cause cache misses

✨ do not mutate the dataframe variables when comparing datetime

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/utils.py
tests/apply_test.py
tests/dtypes_test.py

remove extraction of names from subscript types

---

packages/vaex-core/vaex/agg.py
tests/agg_test.py

This allows things like vaex.agg.sum('x') / vaex.agg.sum('y')

✨ basic math with aggregators

---

packages/vaex-core/vaex/dataframe.py
tests/column_names_test.py

🐛 a column named data was not possible

---

appveyor.yml
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/groupby.py

Small PR to add and improve docstrings
- add docstrings for the `get_group` method of a grouped dataframe
- small modification of the docstrings in the `df.sort` method.

Docs: add & improve docstrings

---

packages/vaex-core/vaex/geo.py
tests/geo_test.py

Created a test for inside_polygon which uses df_factory insead of vaex.from_arrays to simulate loading data from a file. Currently this test fails due to a bug when trying to access dataframe values. 
https://github.com/vaexio/vaex/issues/1592

test(geo): inside_polygon fails when loading from file

---

packages/vaex-core/vaex/array_types.py
tests/evaluate_test.py

You could end up with a list of list instead, or a list of arrow scalars.

🐛 df.evaluate would not convert chunks to lists

---

.github/workflows/pythonpackage.yml
docs/source/api.rst
docs/source/conf.md
docs/source/conf.py
docs/source/index.ipynb
packages/vaex-core/setup.py
packages/vaex-core/vaex/__main__.py
packages/vaex-core/vaex/cache.py
packages/vaex-core/vaex/config.py
packages/vaex-core/vaex/dataset.py
packages/vaex-core/vaex/dataset_mmap.py
packages/vaex-core/vaex/datasets.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/file/cache.py
packages/vaex-core/vaex/memory.py
packages/vaex-core/vaex/multiprocessing.py
packages/vaex-core/vaex/settings.py
packages/vaex-core/vaex/tasks.py
packages/vaex-core/vaex/utils.py
packages/vaex-jupyter/vaex/jupyter/vue/vjsf.vue
packages/vaex-jupyter/vaex/jupyter/widgets.py
packages/vaex-ml/vaex/ml/datasets/__init__.py
packages/vaex-server/vaex/server/fastapi.py
packages/vaex-server/vaex/server/settings.py
tests/settings_test.py

We use pydantic, instead of home grown solutions.
This also includes an experimental widget to see the settings, it does
not store it yet.
See documentation for explanation/usage.

🔨 all settings in Vaex can be configured in a uniform way

---

packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/misc/progressbar.py
packages/vaex-core/vaex/progress.py

and included some small cosmetic changes

🐛 rich progress bar sometimes would not render (too fast)

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/file/asyncio.py
tests/file_test.py

this is useful in combination with e.g. FastAPI where you want to
asynchronously consume and write chunks of data to the socket.
(example/PR for that is coming)

✨ export_arrow on file like objects, and stream as chunks

---

packages/vaex-core/vaex/cache.py
packages/vaex-core/vaex/file/cache.py
packages/vaex-core/vaex/settings.py
packages/vaex-core/vaex/utils.py

✨ put lock files in $VAEX_HOME/lock

---

packages/vaex-core/vaex/datasets/__init__.py

Otherwise converting the taxi datasets it seems vaex is stuck.

 ✨ show progress when converting the included datasets

---

packages/vaex-core/vaex/dataframe.py
tests/export_test.py

I'm not sure if we should use pandas, or not, it deals with things like date time, but we have the issue of nulls/nans. That's why I don't test all columns in the test, because our m column is a None/null, while pandas turns it into a NaN.

✨ export_json

---

.gitignore
packages/vaex-core/setup.py
packages/vaex-core/vaex/dataset.py
packages/vaex-core/vaex/encoding.py
packages/vaex-core/vaex/utils.py

fix: make vaex work with blake3 0.3

---

packages/vaex-core/vaex/progress.py
packages/vaex-core/vaex/settings.py

This will render in the docs, and makes configuration uniformer

✨ progress bar uses settings

---

packages/vaex-core/setup.py

See https://github.com/Marco-Sulla/python-frozendict/issues/48

🐛 frozendict 2.2 on Python 3.6 segfaults

---

docs/source/index.ipynb

Fixes https://github.com/vaexio/vaex/issues/1872

docs: fix broken examples/guides link

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py

Due to https://github.com/dask/dask/pull/7417

🐛 to_dask_array broke with most recent dask (2022.1.1)

---

packages/vaex-core/vaex/dataframe.py

Closes https://github.com/vaexio/vaex/issues/1202

feat(core): Add progress bar to percentile_approx and median_approx

---

packages/vaex-astro/vaex/astro/export.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/geo.py
packages/vaex-hdf5/vaex/hdf5/export.py
packages/vaex-hdf5/vaex/hdf5/writer.py
packages/vaex-ui/vaex/ui/layers.py
packages/vaex-ui/vaex/ui/main.py
packages/vaex-ui/vaex/ui/plot_windows.py
tests/common.py

https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Migrated from https://github.com/vaexio/vaex/pull/1899

remove deprecated numpy bool

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-hdf5/vaex/hdf5/writer.py
tests/fingerprint_test.py

This will be an issue with caching, since it will be stored under
the same cache key.

🐛 fingerprint collision possible if filter uses virtual column

---

packages/vaex-core/src/superstring.hpp
packages/vaex-core/vaex/functions.py
tests/strings_test.py

🐛 strings array growing failed when first string was zero length

---

packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/datatype.py
packages/vaex-core/vaex/encoding.py
packages/vaex-core/vaex/expression.py
tests/datetime_test.py

This was discussed here: https://github.com/vaexio/vaex/issues/1906
Checklist:

Improve filtering of datetime expressions

---

packages/vaex-core/src/hash_string.hpp

perf: avoid hashmap copy

---

.gitmodules
benchmarks/hashmap.py
packages/vaex-core/src/binner_hash.cpp
packages/vaex-core/src/hash.hpp
packages/vaex-core/src/hash_primitives.cpp
packages/vaex-core/src/hash_primitives.hpp
packages/vaex-core/src/hash_string.cpp
packages/vaex-core/src/hash_string.hpp
packages/vaex-core/src/strings.cpp
packages/vaex-core/src/superstring.hpp
packages/vaex-core/src/superutils.cpp
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/hash.py
packages/vaex-core/vaex/json.py
tests/internal/hash_test.py

🐎 store strings in hashmap in arrow array, making map.key_array() faster

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expresso.py
tests/join_test.py
tests/rename_test.py

🐛 test join with colliding function name

---

packages/vaex-core/vaex/functions.py
tests/astype_test.py
tests/isna_test.py

Fix: Support for isnan, isna, ismissing when the underlying data is arrow

---

.github/workflows/pythonpackage.yml
packages/vaex-core/src/binner_ordinal.cpp
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/hash.py
tests/groupby_test.py

This means the resulting dataframe can be presorted, this is useful
if we already know we want the aggregated dataframe to be
sorted afterwards, which is much faster now.

✨(core): all groupers/binner have a sort and ascending argument

---

packages/vaex-core/CMakeLists.txt
packages/vaex-core/setup.py
packages/vaex-core/src/agg.cpp
packages/vaex-core/src/agg_base.hpp
packages/vaex-core/src/agg_count.cpp
packages/vaex-core/src/agg_first.cpp
packages/vaex-core/src/agg_list.cpp
packages/vaex-core/src/agg_minmax.cpp
packages/vaex-core/src/agg_nunique.cpp
packages/vaex-core/src/agg_sum.cpp
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/arrow/convert.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/docstrings.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/groupby.py
tests/agg_test.py

This PR adds new aggregators:
- list aggregator (all the elements from a group are put into a list)
- unique aggregator (the unique elements of the group are put into a list)
Checklist:

feat: add vaex.agg.list aggregator

---

.github/workflows/pythonpackage.yml
packages/vaex-core/src/superstring.hpp
tests/internal/hash_test.py

internally we wouldn't grow the null bitmask

fix: value_counts would give too many null values

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/selections.py
tests/copy_test.py
tests/filter_test.py

```
dff = df[df.some_bool_column]
df2 = df[['some', 'column]]  # this would not take in some_bool_column
```
cc @Ben-Epstein

🐛 filtering by boolean column would miss the column as dependency

---

packages/vaex-core/vaex/expression.py
tests/isin_test.py

This only worked in some cases, like non-ordinal encoded, now it
works consistently for all cases.
@JovanVeljanoski this should fix your streamlit app.

fix: isin should accept empty array or non-existing values

---

packages/vaex-core/vaex/selections.py
tests/filter_test.py

This fixes the issue raise in https://github.com/vaexio/vaex/issues/2038
checklist:

Fix: Filtered dataframes after dropping missing/na values

---

docs/source/example_data_types.ipynb
docs/source/guides.rst

A new guide about data types in Vaex. 
Inspired by https://github.com/vaexio/vaex/issues/2033#issuecomment-1158395026

docs: add guide - data types in vaex

---

packages/vaex-core/vaex/functions.py
tests/strings_test.py

Closes https://github.com/vaexio/vaex/issues/2111

Fix: string join on large_list with large_strings.

---

packages/vaex-core/vaex/dataframe.py
tests/slice_test.py

Fixes https://github.com/vaexio/vaex/issues/2123

Fix: slicing of an empty dataframe

---

packages/vaex-core/vaex/dataframe_protocol.py
tests/dataframe_protocol_test.py

Resolves https://github.com/vaexio/vaex/issues/2120

Interchange `Column.null_count` returns NA count to comply with spec

---

packages/vaex-viz/vaex/viz/mpl.py

Addresses: https://github.com/vaexio/vaex/issues/2142

Fix: improve behaviour of `selection` in `df.viz.histogram`

---

packages/vaex-core/vaex/dataframe.py
tests/unique_test.py

Closes https://github.com/vaexio/vaex/issues/1587

Fix: `unique` with `selection=True`

---

docs/source/tutorial.ipynb

docs: Convenience functions (get_column_names)

---

packages/vaex-core/vaex/__init__.py

Expose vaex.DataFrame and vaex.Expression for typing

---

packages/vaex-core/vaex/dataframe.py
tests/indexing_test.py

Closes https://github.com/vaexio/vaex/issues/2153

Fix: negative index of a filtered dataframe

---

packages/vaex-core/src/agg_nunique.cpp
tests/agg_test.py

Closes https://github.com/vaexio/vaex/issues/2197
Thanks to @vignesh-bungee  making us aware of this.

Fix: nunique agg for numeric with selections

---

packages/vaex-core/vaex/dataframe.py
tests/export_test.py

Add support for the arrow export csv backend in export_many

---

packages/vaex-core/vaex/dataframe.py

The documentation will be updated in a separate PR once we stabilize the methods etc..

Docs: Add missing docstrings to `df.export_csv` and `df.export_csv_arrow`

---

packages/vaex-core/vaex/__init__.py

Raised by https://github.com/vaexio/vaex/issues/2241 so an explicit clarification might be helpful indeed.

docs: update open_many docstring

---

CONTRIBUTING.md

Fix pip install in CONTRIBUTING

---

.github/workflows/pythonpackage.yml
packages/vaex-core/vaex/version.py

Changing to importlib according to this issue:
https://github.com/vaexio/vaex/issues/2211
I was not able to build vex locally yet. Curios about feedback

[FEATURE-REQUEST] Import and version checking improvements  #2211

---

packages/vaex-core/vaex/dataframe.py
tests/extract_test.py

Alternative to #2233
Adresses: #2232

feat: raise when extract cannot run, instead of failing later.

---

packages/vaex-core/vaex/column.py
tests/column_test.py

See discussion at https://github.com/vaexio/vaex/issues/2286
This is largely inspired by the proposal of @NickCrews in https://github.com/vaexio/vaex/issues/2286
Checklist:

Fix: auto-cast to correct type when using vconstant

---

.github/workflows/pythonpackage.yml
.github/workflows/wheel.yml
ci/conda-env.yml
packages/vaex-core/src/agg.hpp
packages/vaex-core/src/hash.hpp
packages/vaex-core/src/hash_object.cpp
packages/vaex-core/src/string_utils.cpp
packages/vaex-core/src/strings.cpp
packages/vaex-core/src/superutils.cpp
packages/vaex-core/vaex/dataframe_protocol.py
packages/vaex-core/vaex/dataset_mmap.py
tests/astro/coordinates_test.py
tests/common.py
tests/fillna_test.py
tests/jupyter/async_test.py

Similar to #2037 except we don't run 3.10 in CI yet.
We can however make a 3.10 binary release with this, and in the meantime sort out CI.

Enable py310
