vaexio/vaex

vaex/dataset.py

in python 3, visual_default.keys() return a dict_keys object which does not have the 'remove' method. .iteritems() does not exist in Python3 anymore.

fix to work in python 3

---

packages/vaex-core/setup.py

See discussion in https://github.com/conda-forge/staged-recipes/pull/4627.

make vaex-core only depend on futures for python 2

---

packages/vaex-core/vaex/__init__.py

The `~/.vaex/vaex_import.py` script doesn't work in python 3, because `execfile` is gone. This replaces it with something that will work in either 2 or 3.

execfile workaround for python 3

---

packages/vaex-viz/vaex/viz/contour.py
packages/vaex-viz/vaex/viz/mpl.py

Using pylab.contour or pylab.contourf, adding support for displaying contours onto the 2D histograms vaex produces. 
I have tried to keep to how other vaex functions have been coded up. 
I hope this helps. 
(no unittests yet, but tested locally to some extent).

Adding support to plot contours on top of the 2D histograms vaex produces.

---

packages/vaex-core/vaex/dataset.py
tests/getattr_test.py

ds[['y', 'x']] would not preserve the order, causing #123 to fail

fix: preserve order columns in getattr/copy and allow expressions

---

packages/vaex-core/vaex/dataset.py
tests/column_names_test.py

get_columns_namesa now expect regex pattern.
All other argumetns still apply. 
```
ds.get_column_names(regex='e*')
```

added regex to get_columns_names()

---

packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/test/dataset.py
tests/serialize_test.py

Wasn't using the registry for serializable function, meaning we would pickle when not needed.

Fix: serialize: function serialize testing was too strict

---

packages/vaex-core/vaex/dataset_mmap.py

`fcntl` is only used inside the `if _nommap:` statement, therefore the import statement can be moved inside the if statement to prevent it from importing when it is not used (which is the case for Windows users).
Fixes #93

Move import fcntl inside if statement.

---

packages/vaex-core/vaex/dataset.py

`from X import *` doesn't import under underscored symbols, so we have
to do this by hand. It would be  better to put this in `.dataframe.__all__`,
but this is less work and `.dataset` is (about to be) deprecated I think.
Fixes #170.

Manually import underscored symbols from .dataframe to .dataset

---

packages/vaex-astro/setup.py
packages/vaex-astro/vaex/astro/transformations.py
packages/vaex-core/vaex/test/dataset.py
setup.py

The kapteyn package is failing to build for python >= 3.7 due to some CYTHON issue in their WCSLib. That breaks the install of vaex-astro.
I propose removing the dependency on kapteyn by assuming static rotation matrices for the coordinate transformations, since the change of Equinox was not even implemented in the first place. 
PS: I changed the setup.py to allow force the --user flag to be passed to subpackages, but I am not sure how to remove it from the pull request.

Remove kapteyn dependency for vaex-astro

---

docs/source/api.rst
docs/source/conf.py
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/scopes.py
packages/vaex-core/vaex/stat.py

Basically a cleanup, bit also provides an API for extending vaex.

Make extending with new functions vaex more convenient

---

packages/vaex-core/vaex/expresso.py
tests/fillna_test.py

Updating a unit-test for `fillna`.
There is a problem when `fillna` is used on an expression, and the output of that operation is overwriting an already existing expression in the DataFrame.

Updating the fillna test for expressions.

---

packages/vaex-core/setup.py

This should fix https://github.com/vaexio/vaex/issues/172
The default `MACOSX_DEPLOYMENT_TARGET` depends on how python is build (found by inspecting distutils sourcecode), my guess is that is different for conda defaults and conda-forge, because all of the sudden it was 10.7 for me. This will set it to 10.9 if not explicitly set.

Fix building osx

---

packages/vaex-arrow/vaex_arrow/dataset.py
packages/vaex-arrow/vaex_arrow/export.py
packages/vaex-arrow/vaex_arrow/opener.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/test/dataset.py
tests/export_test.py

This allows exporting to parquet support, which is useful when if we want to benchmark against spark for instance.
Reading will be all in memory, so it may not yet be good for large datasets.
Once we have a usecase for a really large datasets in Parquet, for instance partitioned datasets, we can take another look at reading efficiently.

New feature: Initial Parquet support

---

packages/vaex-core/vaex/formatting.py

The printing of `datetime` and `timedelta` data types is no longer dependent on `pandas`.
Thus, `pandas` is no longer a hard dependency for `vaex`, which fixes #209 
This is how the printing looks like after the update:

remove pandas dependency in formatting

---

packages/vaex-core/src/vaexfast.cpp

This makes sure vaex does not segfaults, as reported by  #208

fix: make sure percentile and median do not segfault

---

packages/vaex-core/vaex/dataframe.py
tests/count_test.py

Small fix in the `dataframe._binner```, causing string based limits to be parsed weirdly, if they are of string type (like percentages, minmax etc.).

Small fix in the dataframe._binner

---

packages/vaex-core/vaex/dataframe.py

Fixes the `df.info()` where in the column description table the type of the string columns was not displayed.

Fixes the info panel where the string types were not being displayed

---

packages/vaex-core/vaex/groupby.py
tests/groupby_test.py

Adding a `groupby` which tests for the consistency of results when the group is made on a feature extracted from a datetime column. There is sometimes a problem when the `df.executor.buffer_size` is much smaller than the number of rows in that `df`.

groupby rows consistency test

---

packages/vaex-core/vaex/expression.py
tests/datetime_test.py

This PR adds a unit-test checking the basic arithmetic operations between a `vaex.Expression` of type `timedelta64` and `numpy.timedelta64`.

Timedelta operations

---

packages/vaex-core/vaex/settings.py

Small fix to remove the deprecation warning from vaex-core/vaex/settings.py to remove the deprecation warning coming from importing the `collections.abc` module. 
The same fix was already applied in vaex-core/vaex/expression.py

Remove deprecation warning due to collection.abc import

---

packages/vaex-core/vaex/json.py
packages/vaex-core/vaex/remote.py
packages/vaex-core/vaex/utils.py
tests/state_test.py

This allows datatime64 and timedelta64 objects to be serialized. It should be easy to extend this for other types using the `@register` decorator.

Fix datetime state serialize

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/scopes.py
packages/vaex-core/vaex/test/dataset.py
tests/slice_test.py

First, because of an issue in using the logger, repr(df) was being called for each tasked added to the executor (even when no logging was done). This will improve performance of filtered datasets a lot.
Second, selections, and especially filter are more efficient to use. Since filter will not be modified, they can share the filter mask and cache when a shall copy is made (`df.copy()` which is used a lot internally in vaex). Also, the selections chunck caches (filtering also makes use of that) gets (shallowly) copied into the new dataframe, allowing copies to not have to recompute the masks.
```python
df = df[df.x>0] # nothing is done
print(len(df)) # now the mask is filled
df = df[df.x < 10]
print(len(df)) # now only the new filter is computed (df.x < 10)
```
If you do all filtering …

Big filter performance improvements

---

packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
tests/map_test.py

This give the user support to pre-define how values not defined in the mapper are to be handled. By default, and exception is raised, but any other default values can be specified.

Adding support for "unmapped" values in map method.

---

packages/vaex-core/vaex/dataframe.py
tests/fillna_test.py
tests/rename_test.py

A unit-test exposing a potential problem when the `fillna()` method is used on a virtual expression, where the virtual expression contains `nan` values as a result of the calculationnot tri.
Note that the unit-test does trigger a failure: due to the nature of the problem `pytest` does not register the test at all, but looking at the logs one can easily spot the problem.

Unit-test for fillna() when the expression is virtual.

---

packages/vaex-core/vaex/functions.py
tests/rename_test.py
tests/strings_test.py

This is a simple check for `repr` for `str.slice`. Currently this is not supported, but I think it would be great to support it, and check preview of operations.

Unit-test for str.slice, checking for repr.

---

packages/vaex-core/vaex/expression.py

The error message now also states the total number of values that are missing from the mapper in 
`vaex.expression.map()`.

Improve error message for missing values in .map()

---

packages/vaex-core/vaex/__init__.py
tests/from_json_test.py

Adding a `from_json` method, allowing to read JSON files directly into a `vaex` DataFrame.

Adding a from_json method

---

packages/vaex-core/vaex/expression.py
tests/datetime_test.py

Adding the possibility to perform binary operations with `numpy.datetime64` instance.
e.g.:
```
df.startDate > np.datetime64('2019-05-05')
```
will not result in an expression.

binary operations with numpy.datetime64 instance

---

packages/vaex-core/vaex/dataframe.py
tests/trim_test.py

This fixes error for e.g.:
```
ds = vaex.example()
ds['r'] = (ds.x + ds.y) / (ds.z * 5)
ds[['r', 'x']].head(5)
```

fix(core,trim): trimming didn't trim hidden columns

---

packages/vaex-core/vaex/dataframe.py
tests/slice_test.py

Update of the unit-test for slicing DataFrames and Expressions, highlighting slicing options that are not yet supported.

Slicing dataframes and expressions (reloaded)

---

packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-ml/vaex/ml/transformations.py
tests/ml/ml_test.py

This PR makes improvements on the implementation of `vaex.ml.LabelEncoder()`. It leverages the super fast `map` method. and runs fully out of core. There is now support for values that were not present during the training (fitting) stage. 
The past implementation was not fully out of core as far as I can tell.
Also, there is a small adjustment to the unit-test. The encoder is longer tested against the `sklearn`s implementation, for the simple reason that the order of the unique elements (categories) in a feature is not guaranteed to be the same in `vaex` and `sklearn`. However, I am comfortable with this, since the `map` method is properly tested.

Improving the LabelEncoder

---

packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
tests/countna_test.py
tests/isna_test.py

[Edited]
This PR adds `veax.expression` methods:
- `isna()` which returns a boolean expression in which an element is `True` if it is not available (N/A) (either `None` or `np.nan`);
- `notna()` which returns a boolean expression which is opposite of `notna()`;
- `countna()` which returns the number of not available (N/A) values (either `None` or `np.nan`).
Each of the methods comes with a unit-test.

isna(), notna(), countna() methods for `vaex.expression`

---

packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/utils.py
tests/jit_test.py

This is the start of CUDA/GPU support.
We can use jit_cuda() on expression to have the GPU do the calculations, e.g. on 1.7 billion rows of the Gaia DR2 dataset:
In this case, the speedup is >2x. My initial reaction was that it cannot be true, it was too slow, but comparing single threaded numpy to cupy, these numbers seem to be correct.
The 'issue' is that vaex is already quite fast, and multithreaded by default. Note that these benchmarks were run on a 6core machine with a GTX 1050 Ti (x1 extreme).

CUDA GPU support

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/remote.py
packages/vaex-core/vaex/serialize.py
packages/vaex-core/vaex/test/dataset.py
packages/vaex-core/vaex/webserver.py
packages/vaex-ml/vaex/ml/catboost.py
packages/vaex-ml/vaex/ml/incubator/annoy.py
packages/vaex-ml/vaex/ml/incubator/pygbm.py
packages/vaex-ml/vaex/ml/lightgbm.py
packages/vaex-ml/vaex/ml/state.py
packages/vaex-ml/vaex/ml/xgboost.py
tests/server/token_test.py

to make deserialization safer
* If no token_trusted is passed to the server, the server will not trust during state_set, and
will not deserialize pickled states.
* If token of token_trusted is set, a user needs to provide either one of them.
Usage for server:
```
$ vaex webserver ~/datasets/gaia/STSci/gaia_ps1_subset.hdf5  --token-trusted=mytoken
```
From Python:
```
df = vaex.open('ws://0.0.0.0:9000/gaia_ps1_subset?token_trusted=mytoken')
df.x.apply(lambda x: x+1).sum()
```
Now the lambda function will get deserialized at the server, otherwise it is now allowed.
Use `--token` to protect the server from any user, but disallow unsafe deserialization.
Use case: run a server, share a token to a group of semi-trusted users/tests, and use the `--token-trusted` to give yourself and a group of …

feat(core,server): server takes token and/or token-trusted

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/functions.py
tests/describe_test.py
tests/value_counts_test.py

This PR is to highlight and patch a bug which happens when counting the number of missing values in  `dataframe.describe()`, which happens when the `expression` is of `dtype` `O`.

Test for counting missing value in dataframe.describe()

---

packages/vaex-arrow/vaex_arrow/convert.py
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
tests/dtypes_test.py

This will allow the csv in https://towardsdatascience.com/a-billion-rows-a-second-36b7a2066175?gi=d0ff8b86a706 to be loaded in 1 line: `df = vaex.open('/path/to/file.cvs.bz2', convert='file.hdf5')`

feat(core): better string detection for dtype=object

---

packages/vaex-core/vaex/expression.py
tests/jit_test.py

e.g. when doing
df['a'] = df.a.jit_cuda()
df['a'] = (df.a*2).jit_cuda()
It wouldn't not process that correctly

fix(core): allows overwriting jitted functions

---

packages/vaex-core/vaex/__init__.py
tests/open_test.py

avoid errors like the following when opening unsupported formats
```
In [148]: vaex.open('events-80kk.jsonl', convert='events-v.hd5')   
ERROR:MainThread:vaex:error opening 'events-80kk.jsonl'
-------------------------------------------------------------------
AttributeError                    Traceback (most recent call last)
<ipython-input-148-fd088de8f507> in <module>
----> 1 vaex.open('events-80kk.jsonl', convert='events-v.hd5')
~/devel/feedstock/ep2019/virtual/lib/python3.6/site-packages/vaex/__init__.py in open(path, convert, shuffle, copy_index, *args, **kwarg
s)
191                         ds = vaex.file.open(path, *args, **kwargs)
192                     if convert:
--> 193                         ds.export_hdf5(filename_hdf5, shuffle=shuffle)
194                         ds = …
```

Improve error on open unsupported formats

---

tests/ml/catboost_test.py

This makes a `catboost` unit-test be more robust to changes its performance.

Improve catboost unit test

---

packages/vaex-astro/setup.py
packages/vaex-astro/vaex/astro/legacy.py
packages/vaex-astro/vaex/astro/transformations.py
packages/vaex-core/setup.py
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/geo.py
packages/vaex-jupyter/setup.py
packages/vaex-jupyter/vaex/jupyter/__init__.py
packages/vaex-ml/setup.py
packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-viz/setup.py
packages/vaex-viz/vaex/viz/__init__.py
tests/internal/accessor_test.py
tests/ml/catboost_test.py
tests/ml/lightgbm_test.py
tests/ml/sklearn_test.py
tests/ml/xgboost_test.py

This change will make it easier for us, and 3rd parties to add new dataframe accessors to vaex, without increasing import time.
Adding an entry point to setup.py `{'vaex.dataframe.accessor': ['geo = vaex.geo:DataFrameAccessorGeo']}` will only import vaex.geo when df.geo is accessed, this will speed up importing time of vaex, since before we eagerly imported all `vaex.namespace` plugins (which is now deprecated). Note that the 'normal' way of adding an accessor `vaex.register_dataframe_accessor` is still supported.
I think by now we should think of creating a section in the documentation for extending vaex.
Also, 'nested' accessors are now supported, e.g.:
```
entry_points={
'vaex.dataframe.accessor': ['geo.cone = ectopylasm.vaex:ConeAccessor']
}
```
We also do not have to import vaex.ml, …

feat: lazy df accessor plugin system

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/utils.py
packages/vaex-hdf5/vaex/hdf5/dataset.py
tests/column_names_test.py

Implemented using a df._column_aliases dict that will translate those names
when possible.
Note that it means that you cannot do:
```
df['class * 2']  # this expression cannot be parsed
```
but instead, you can do
```
df['class'] * 2  # this can use the aliasing
```
If for some reason you need to write an expression using strings, use:
```
expression_string = str(df['class']) + ' * 2'
```
Closes #253,  should also help with #369

feat(core, hdf5): support python keywords and invalid variable names

---

docs/source/api.rst
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/geo.py
tests/timedelta_test.py

Adding support for methods on `timedelta` columns. For the moment, the support is added via 
`pandas` (just like for the `datetime` operations).
New accessor is added, `td` "timedelta" which houses these method. 
The following example describes the usage.
```
>>> import vaex
>>> import numpy as np
>>> delta = np.array([17658720110,   11047049384039, 40712636304958, -18161254954], dtype='timedelta64[s]')
>>> df = vaex.from_arrays(delta=delta)
>>> df
0  204 days +9:12:00
1  1 days +6:41:10
2  471 days +5:03:56
3  -22 days +23:31:15
>>> df.delta.td.days
Expression = td_days(delta)
Length: 4 dtype: int64 (expression)
-----------------------------------
0  204
1    1
2  471
3  -22
```

Adding support for timedelta operations (methods)

---

packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/dataframe.py
tests/agg_test.py

With this PR we add `selection` arguments to the aggregators, i.e. `vaex.agg` methods. 
This will enable very flexible way of aggregating columns, for instance
```
df.groupby(df.x).agg({'y_mean_sel': vaex.agg.mean(df.y, selection='z > 10')})
```
In the above example, the `y_mean_sel` column will have the mean only of those values that pass the selection condition. This can be done per aggregation operation, offering great flexibility.

Support for selections in vaex.agg functions

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/tasks.py
packages/vaex-core/vaex/utils.py
tests/masked_values_filters_test.py
tests/strings_test.py

This PR fixes the behaviour of selections and filtering when done on columns that contain masked values. 
In the current version, selections and filtering seem to often just pass-through the rows that contain missing values. Consider the following example:
```
>import numpy as np
>import vaex
>x = np.ma.MaskedArray(data=[0, 1, 2, 3, 4], mask=[False, False, True, False, True])
>y = np.ma.MaskedArray(data=[3, 5, 2, -1.5, 0], mask=[False, False, False, False, False])
>df = vaex.from_arrays(x=x, y=y)
>print(df)
0   0     3
1   1      5
2   --    2
3   3     -1.5
4   --    0
>df_filter = df[df.x >= 1] 
>print(df_filter)
0   1      5
1   --     2
2   3     -1.5
3   --    0
```
As one can see the `df_filtered` dataset contains the rows that should have been filtered out, similar to if instead of …

Filtering and selections when done on columns with masked values

---

packages/vaex-core/vaex/column.py

This fixes mem issues when joining dataframes with lots of columns on the right.

fix(core): double indices columns were not using index cache since empty dict is falsy

---

tests/unique_test.py

Unit-test for `unique`, which tests the behaviour in case of `dtype` `object` and the presence of n/a data (`np.nan`, `None`).

Unit-test for unique in case of dtype object and n/a values

---

packages/vaex-core/src/strings.cpp
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/functions.py
tests/internal/strings_module_test.py
tests/value_counts_test.py

Correcting the behaviour of `value_counts` for `str` column that contains masked values and empty strings

value_counts of column that contains masked values and empty strings. 

---

packages/vaex-core/vaex/dataframe.py
tests/describe_test.py

At the moment the `describe` method does not detect `pandas.NaT` (not a time) values as N/A. This unit-test exposes this.

Unit-test: add pd.NaT towards the total count of NA in describe()

---

packages/vaex-graphql/LICENSE.txt
packages/vaex-graphql/MANIFEST.in
packages/vaex-graphql/setup.py
packages/vaex-graphql/vaex/graphql/__init__.py
packages/vaex-graphql/vaex/graphql/__main__.py
packages/vaex-graphql/vaex/graphql/_version.py
packages/vaex-graphql/vaex/graphql/tornado.py

This adds the vaex-graphql package, that adds graphql support to query vaex.
GraphQL is really nice to have a standard way to query data, that is not as general as SQL, but also allows us to implement binby, and anything custom we need. Interfacing with frontends is really simple, a ton of libraries are out there.
e.g.
```python
result = df.graphql.execute("""
{
df {
min {
x
y
}
mean {
x
y
}
max {
x
y
}
}
}
""")
assert data['df']['min']['x'] == df.x.min()
```
Although it does not depend on tornado, it adds an option to quickly show this using the graphiql interface, you'd have to install:
```
$ pip install graphene-tornado
```
Then run
```
$ python -m vaex.graphql ~/datasets/nyc_taxi2015.arrow
```
Which should give you a url, to a webinterface:
All aggregations are done serially for now. …

GraphQL support

---

.travis.yml
packages/vaex-core/vaex/groupby.py
packages/vaex-jupyter/vaex/jupyter/state.py
packages/vaex-jupyter/vaex/jupyter/traitlets.py
packages/vaex-ml/vaex/ml/transformations.py
tests/column_names_test.py

When we run the unit tests we see lots of deprecation warnings. These are mostly from external dependencies, but few do come from vaex. In this PR I am cleaning up the vaex deprecation warnings:

Clean up deprecation warnings

---

packages/vaex-graphql/vaex/graphql/__init__.py
tests/graphql_test.py

This adds a subclass to directly support pandas

feat(graphql): make accessor work for pandas dataframes directly

---

.travis.yml
packages/vaex-core/vaex/dataframe.py
tests/rename_test.py

stays the same, and the new name isnot accessible.

Fixes for issues related to renameing columns

---

packages/vaex-core/setup.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
tests/dask_array_test.py

Allow converting a dataframe to a 2d dask array, or an expression (lazily) to a 1d dask array.
Example:
```python
Xd = da.sin(df.to_dask_array())
xd = da.sin(df['x'].to_dask_array())
```
Note that vaex also accepts dask arrays as input, but will directly cast/computes them to a numpy array via np.asanyarray/

Dask array support

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
tests/rename_test.py

Before, if you did:
```python
x = df.x
df['x'] = df.x**2
```
`x` would 'change', i.e. if would refer to the square of x, which I think is unexpected. I think it is better to have array semantics, meaning that the expression object `x` would always refer to the 'values' if had.
To implement this, the expression behind the object (`x.expression`) will be rewritten.
Note: this is required for #415 to work, since the dot product will assign to a column, while expecting the original expressions to still refer to the 'old' values.

fix(core): existing expressions are rewritten, to make them behave like arrays

---

packages/vaex-core/vaex/scopes.py

Much faster to test if a variable is in the `df.columns` dict.
This is an overall performance increase, especially for dataframes with many columns.

perf(core): avoid calling df.get_column_names (1000x for 1 billion rows per column use)

---

packages/vaex-core/vaex/dataframe.py

Improved the performance of below snippet by factor of ~5.
```python
df = vaex.open('/Users/maartenbreddels/datasets/nytaxi/nyc_taxi2015.hdf5')
dff = df[df.passenger_count>0]
display(dff[1:-1])
```

perf: slicing e.g df[1:-1] goes much faster for filtered dataframes

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/expresso.py
tests/expression_variables_test.py
tests/getattr_test.py

#415 is quite slow because each time expressions (strings) need to be compiled to find out dependencies, and also rewriting expression were slow.
By caching the ast, and keeping a dict of name->ast node we can do many of these operations faster.
TODO: needs cleanups.

refactor(core): dataframe copying and expression rewriting was slow

---

packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/export.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/remote.py
packages/vaex-core/vaex/tasks.py
packages/vaex-core/vaex/utils.py
packages/vaex-hdf5/vaex/hdf5/export.py
tests/concat_test.py
tests/graphql_test.py
tests/strings_test.py
tests/trim_test.py

Evaluate has become quite a beast, but there need to be 2 modes, parallel (default for users), and non-parallel (interally mostly, but also if someone else already does the multithreading).
For vaex internally, if it's in a task (say map reduce), it can call `df.dtype(..)`, which may call `df.evaluate`, which will start another task, which is not supported.
These are the two reasons why evaluate has a parallel and non-parallel mode.

feat(core): parallel evaluate

---

packages/vaex-core/vaex/dataframe.py

also, since dask will be multithreaded by itself, we don't want the evaluate to be multithreaded/parallel.

fix(core): converting to dask array was missing a to_arrays()

---

.github/workflows/pythonpackage.yml
.travis.yml
appveyor.yml
requirements-ml.txt

Do to recent changes in `catboost`, we need to limit it to version <0.20. 
Please see #481 for more details.

Limit catboost version to <0.20

---

packages/vaex-core/vaex/dataframe.py
tests/fillna_test.py

Desired functionality for fillna in a standard use case.
```
df['x'] = df.x.fillna(float(df.x.mean()))
```
vs
```
df['x'] = df.x.fillna(df.x.mean())
```

Fillna df.mean() compatibility test

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/selections.py
tests/selection_test.py

The first feature is to refactor `df[<expr>]` to make use of the more general df.filter, which is analogous to `df.select`, and allows filter to 'grow the selection' (i.e. select **more** rows), which would never be possible with numpy/pandas, or any framework that uses immediate evaluation and memory copies. Also, by allowing selections/filters so have boolean scalar values (such as dataframe variables), we can create really flexible filters:
This enabled filters to be as flexible as selections, e.g.:
```python
df = df[df.x>4]
df.add_variable("production", False)
df = df.filter("production", mode="or")
```
By transferring this state to another dataframe, and setting the variable `production` to True, we affect the filter (in this case disable it, since production will evaluate to True …

Feat filter options

---

packages/vaex-ml/vaex/ml/catboost.py
packages/vaex-ml/vaex/ml/lightgbm.py
packages/vaex-ml/vaex/ml/sklearn.py
packages/vaex-ml/vaex/ml/xgboost.py

The lazy function in the vaex-ml model predictors wrappers is now made unique. This allows for the wrappers to be used multiple times in different context (different features, different parameters etc..) in the same runtime.

vaex-ml: Lazy function in predictors is made unique

---

CHANGELOG.md
packages/vaex-core/vaex/core/_version.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-meta/setup.py
packages/vaex-meta/vaex/meta/_version.py
tests/join_test.py

Remove duplications of columns when joining DataFrames on the same column name:

Duplicated columns when joining on the same column name

---

CHANGELOG.md
packages/vaex-meta/setup.py
packages/vaex-ml/vaex/ml/_version.py
packages/vaex-ml/vaex/ml/sklearn.py
tests/ml/sklearn_test.py

This PR adds a `veax.ml.sklearn.IncrementalPredictor` class that wraps any `scikit-learn` estimator (a.k.a predictor) that has the `.partial_fit` method. 
This means that we can send batches of data from `vaex` to such a predictor, while controlling the memory needed. 
Each batch can be "seen" by the predictor multiple times (epochs), and optionally it can be shuffled.

feat(ml): IncrementalPredictor

---

docs/source/ml.ipynb

Fixed a typo in the one hot encoder example

fix(ml.ipynb): fixed a typo in the one hot encoder example

---

packages/vaex-core/vaex/functions.py
tests/datetime_test.py

PR handling the creation of a `np.datetime64` column from several `str` columns. 
Related to #368

fix(core): astype can create datetime64 columns out of (arrow) string array

---

packages/vaex-core/src/strings.cpp
tests/strings_test.py

Adding a test which exposes an issue when doing string operations on an expression of dtype str. The issue appears when at least one of the elements in the expression is `None`, and the data is read from hdf5 or arrow file.

Fix: invalid mask access triggered when memory mapped read only

---

CHANGELOG.md
packages/vaex-core/src/superutils.cpp
packages/vaex-core/vaex/core/_version.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/utils.py
packages/vaex-meta/setup.py
packages/vaex-meta/vaex/meta/_version.py
packages/vaex-ml/setup.py
packages/vaex-ml/vaex/ml/_version.py
packages/vaex-ml/vaex/ml/sklearn.py
tests/evaluate_test.py
tests/internal/chunking_test.py

This introduces parallel chunking support for evaluate. e.g.:
```
>>> import vaex
>>> df = vaex.example()
>>> for i1, i2, chunk in df.evaluate_iterator(df.x, chunk_size=100_000):
...     print(f"Total of {i1} to {i2} = {chunk.sum()}")
...
Total of 0 to 100000 = -7460.610158279056
Total of 100000 to 200000 = -4964.85827154921
Total of 200000 to 300000 = -7303.271340043915
Total of 300000 to 330000 = -2424.65234724951
```
An implementation default that matters, by default prefetch=True, meaning that before the first chunk is yielded, the second chunk will already start computing. This means that if the main thread if single-threaded (e.g. some scikit-learn algorithm), we make maximum use of the CPU. 
Speedup seen on 1 billion rows: before 12 minutes, after 6.

Feat:  evaluate iterator / parallel chunking

---

.github/workflows/pythonpackage.yml
.travis.yml
CHANGELOG.md
appveyor.yml
requirements-ml.txt

The latest version of CatBoost remedies the issues described in #481 , and thus we are allowing the latest version of CatBoost to be installed as part of the CI testing.

Allow latest version of CatBoost in CI

---

CHANGELOG.md
packages/vaex-ml/vaex/ml/sklearn.py
tests/ml/sklearn_test.py

This PR renames `vaex.ml.sklearn.SKLearnPredictor` to `vaex.ml.sklearn.Predictor`

Rename SKLearnPredictor to Predictor

---

CHANGELOG.md
packages/vaex-ml/vaex/ml/sklearn.py

Small improvements in the `vaex.ml.sklearn.IncrementalPredictor`

Improve IncrementalPredictor 

---

docs/source/tutorial.ipynb
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-ml/vaex/ml/xgboost.py

Fix some typos or styling in the text of the [Vaex tutorial](https://docs.vaex.io/en/latest/tutorial.html) and [API](https://docs.vaex.io/en/latest/api.html).

Fix several typos in the documentation

---

CHANGELOG.md
packages/vaex-core/src/strings.cpp
packages/vaex-core/vaex/column.py
tests/column_test.py
tests/join_test.py

This PR is tackling #528.
This issue occurs when the data is memory-mapped. It has to do with the string columns of the resulting joined dataframe having missing values, since the two dataframes being joined to each other do not correspond 1:1.

Fix: join issue when data is memory-mapped.

---

CHANGELOG.md
packages/vaex-ml/vaex/ml/sklearn.py
tests/ml/sklearn_test.py

A small fix in `vaex.ml.sklearn.IncrementalPredictor` so it can be used with `sklearn.linear_model.SGDClassifier`.  This requires that the classes are passed to the `.partial_fit` method of the scikit-learn model.

Fix IncrementalPredictor to work with classifiers

---

CHANGELOG.md
docs/source/api.rst
packages/vaex-meta/setup.py
packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-ml/vaex/ml/_version.py
packages/vaex-ml/vaex/ml/transformations.py
tests/ml/ml_test.py

Implementation of `CycleTransformer`. 
This is useful for encoding cyclical features (angles, time etc.) for machine learning tasks. The idea is to think of such circular features as the angle of a unit circle in polar coordinates, and then make projection on the x and y axes. This preserves the continuity (January is as close to December as it it is to February for example). For each encoded feature, two new ones are created.

Cyclical features transformer

---

CHANGELOG.md
docs/source/api.rst
packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-ml/vaex/ml/transformations.py
tests/ml/ml_test.py

This PR implements a Bayesian Target Encoder. This is a variant of the mean target encoding scheme which fights over-fitting by smoothing the encoded values of each category towards the global mean of the target variable. The strength of the smoothing is adjusted by setting a prior (`weight`). If this is set to 0, no such smoothing is applied, and only a mean target encoding is applied.

Bayesian Target Encoder

---

CHANGELOG.md
docs/source/api.rst
packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-ml/vaex/ml/transformations.py
tests/ml/ml_test.py

This PR implements a Weight of Evidence categorical encoder.
Weight of Evidence measures how well a particular feature supports the given hypothesis (i.e. the target variable). With this encoder, each category in a categorical feature is encoded by its "strength" i.e. Weight of Evidence value.

WeightOfEvidenceEncoder implementation

---

CHANGELOG.md
packages/vaex-core/vaex/misc/progressbar.py
packages/vaex-core/vaex/multithreading.py
packages/vaex-core/vaex/utils.py
tests/progress_test.py

Refactored our own (old) progress bar a bit so the widget version can use much of the same logic.
The widget version also has cpu usage, which is the cpu usage between start end end:

feat(core): progress update

---

.gitignore
tests/ml/ml_test.py

This is a small fix for the appveyor CI. There is some strange issue in numpy in some 1.17.x versions that is causing our RobustScaler tests to fail.

Fix for CI (windows)

---

tests/ml/ml_test.py

Yet another CI fix for windows, due to a numpy issues (RobustScaler in ml).

Skip robust scaler test in windows for numpy <= 1.18.1

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
tests/from_json_test.py
tests/to_test.py

This is useful for outputting to csv or arrow very large dataframes
with virtual columns that cannot be kept into memory.
Example usage for csv:
```python
import vaex
df = vaex.open('s3://vaex/taxi/yellow_taxi_2009_2015_f32.hdf5?anon=true')[:1_000_000]
df = df[['passenger_count', 'fare_amount', 'pickup_datetime']]
for i1, i2, pdf in df.to_pandas_df(chunk_size=100_000):
fn = f'taxi_{i1}-{i2}.csv'
print(fn)
pdf.to_csv(fn)
```
Or outputting to parquet
```python
schema = df[0:1].to_arrow_table().schema
with pq.ParquetWriter('example.parquet', schema) as writer:
for i1, i2, table in df.to_arrow_table(chunk_size=100_000):
print(i1, i2)
writer.write_table(table)
```
Note that we probably want a nicer way to get the arrow schema. Also, we yield the row indices, should we also yield the …

feat: let to_items/pandas_df/arrow_table return chunked iterators

---

benchmarks/from_pandas.py
packages/vaex-core/vaex/dataframe.py

This change improves the performance of `vaex.from_pandas` further on top of the improvement made in #612: from 1.76 to 2.86 million rows per second on the NYC Taxi data of around 1.8 Gb.

Perf(core): even more efficient check for types in a column when creating a DataFrame

---

packages/vaex-core/vaex/multithreading.py
packages/vaex-server/vaex/server/executor.py
packages/vaex-server/vaex/server/tornado_server.py
tests/progress_test.py
tests/server/basics_test.py

Also, they did not propagate to the client, and remote dataframe calculations were accidentally cancelled.

fix: cancelled calculations were not stopped

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
tests/column_test.py

This PR makes `df.column_count()` to not count hidden columns in the DataFrame

Make df.column_count to not count hidden columns

---

tests/concat_test.py

This addresses #529 
The issue happens when trying to display portion of a concat dataframe with `.head` or `.tail` methods of a dataframe that contains missing values.

Fix head/tail for concatenated DataFrames with missing values

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
tests/agg_test.py

This is to be in line with #654 and the binby supporting xarray.
Example:
Also, this integrates well with plotly express' latest xarray support (cc @nicolaskruchten):

feat: support xarray format for quick aggregators (e.g. df.count(..))

---

packages/vaex-core/vaex/dataframe.py
tests/values_test.py

When a dataframe (the whole dataframe, not an expression) is evaluated with the `.values` method, if a column contains masked values, those values will be realized as some numeric values (i think the masked values is filled with some large number). In the case of `numpy.ma.MaskedArray`, i expect the masked values to be "translated" to `np.nan`. This is what the unit-test assumes. 
This may be related to #639 although I am not quite sure. 
Checklist:

Fix: evaluation of a dataframe containing masked arrays

---

packages/vaex-core/vaex/dataframe.py
tests/state_test.py

This PR handles the issue report in #591

Fix state transfer after rewriting virtual columns

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
tests/count_test.py

This PR fixes a potential issue with `df.count(expression=some_expression, limit='minmax')`
This issue is especially apparent when there is a selection applied to the dataframe.

Fix: `count` issue with `limits='minmax'`

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
tests/percentile_approx_test.py

Update the functionality of `dataframe.percentile_approx`:

Improve the API for the percentile_approx dataframe method

---

.github/workflows/pythonpackage.yml
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/geo.py
tests/geo_test.py
tests/jupyter/widget_core_test.py

feat(core): df.geo polygon testing

---

CHANGELOG.md
packages/vaex-core/vaex/agg.py
tests/groupby_test.py

`df.groupby(by=df.g, agg=[vaex.agg.mean(df.long_name)]).sort('g')` led to a column name `l_o_n_g__n_a_m_e_mean`.

fix: Using automatic names for aggregators led to many underscores in name

---

packages/vaex-core/vaex/dataframe.py
tests/export_test.py

This PR adds `.export_csv` method to the dataframe.
For DataFrames that are too large to fit in memory, the export is done in chunks, so one only needs to have enough disk space to house the output file.

Feature: export_csv

---

packages/vaex-arrow/vaex_arrow/convert.py
tests/arrow/to_arrow_table_test.py

This is to fix a flaky/inconsistent evaluation of expressions using the `to_arrow_table` method. 
The better summarize the issue:
- It happens only (to the best of my knowledge) when an expression is make of masked arrays, or is a virtual column calculated on the basis of masked arrays
- Not sure if it happens if the evaluation is *not* in chunks
- Does not happen if the `chunk_size` is very small (like less than 5 or so)
- Happens more rarely if the `chunk_size` is large compared to the size of the dataset (like 50% of the df size or more), although I can not guarantee this in all cases. 
- This does not seem to be the case with other types of missing values like `None` and `np.nan`.
I made a unit-test exposing this. Not the most concise of test, but this is the most I could narrow the …

Fix: inconsistent evaluation in to_arrow_table

---

packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/dataframe.py
tests/agg_test.py
tests/to_test.py

Next to df.count(..., array_type='xarray'), we also can do df.count(..., array_type='list').
We also have support for array_type in df.to_dict(..), so it's easier to JSON serialize.

feat: df.to_items df.to_dict support array_type, and added array_type=list

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/test/dataset.py
tests/evaluate_test.py

This PR improves the data evaluators (i.e. the `to_dict`, `to_items` et.. method), by making them more consistent with each other. 
Work done:

Feat: Improve the data evaluators

---

benchmarks/README.rst
bin/benchmark_new_commits.sh

Implement a script and instructions to run benchmarks as a cron job on dedicated hardware.
* Test all the new commits on `master`
* Test any commits on `bench*` branches in the base repo: to measure WIP performance improvements
* Publish results to the http://asv.vaex.io/
* Save results in the `gh-pages` repo for history
@maartenbreddels I have done some of the items from the [Initial setup of the machine](https://github.com/byaminov/vaex/blob/d0808e04415959df2659a467d894514264bc7064/benchmarks/README.rst#initial-setup-of-the-machine), but some you will have to do yourself, as you have permissions:
(2.) Add SSH key of `github` user as a [Deploy key](https://github.com/vaexio/vaex/settings/keys).
(3.) Clone the repo
(7.) Run ASV for the first time
(8.) Modify the cron job if you want a …

chore: run benchmarks on dedicated hardware

---

CHANGELOG.md
packages/vaex-core/vaex/functions.py
tests/datetime_test.py

As per the title and in regards to [issue 679](https://github.com/vaexio/vaex/issues/679), this PR adds the `dt.strftime` (get formatted strings out of datetime) and `dt.quarter` (get the quarter a datetime belongs to) functionality.
I added a new function `test_create_str_column_from_datetime64()` since I wasn't sure where the test would be most appropriately placed. Might be overkill (plus is there some driver program somewhere that I should also touch if a new test function is added?), but let me know what you think.

Add dt.strftime and dt.quarter

---

CHANGELOG.md
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/export.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/misc_cmdline.py
packages/vaex-core/vaex/tasks.py
packages/vaex-core/vaex/test/dataset.py
packages/vaex-hdf5/vaex/hdf5/export.py
packages/vaex-jupyter/vaex/jupyter/traitlets.py
packages/vaex-server/vaex/server/service.py
packages/vaex-ui/vaex/ui/columns.py
packages/vaex-ui/vaex/ui/variables.py
tests/concat_test.py
tests/dtypes_test.py
tests/strings_test.py

… use df.data_type(), df.expr.dtype is still behaving the same
This allows us to use .dtype for behaving as a numpy array (see NEP branch)
and to later add in support for other data_types, not just numpy (arrow, Python, ...)

refactor!: df.dtype is a property, to get data types for expressions

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/version.py

eg
```
$ python -c "import vaex; print(vaex.__version__)"                                                              
{'vaex': '3.0.0.dev0', 'vaex-core': '2.0.0.dev0', 'vaex-viz': '0.4.0.dev0', 'vaex-hdf5': '0.6.0.dev0', 
'vaex-server': '0.3.0.dev0', 'vaex-astro': '0.7.0.dev0', 'vaex-ui': '0.3.0', 'vaex-jupyter': '0.5.0',
'vaex-ml': '0.9.0.dev0', 'vaex-distributed': '0.3.0', 'vaex-arrow': '0.5.0.dev0', 'vaex-graphql': '0.1.0.dev0'}
```

Chore: version fix

---

packages/vaex-core/vaex/column.py
tests/column_test.py
tests/join_test.py

Adds a test that exposes a bug with left join when the right dataframe is filtered. 
Originally reported in #732

Fix: Left join when the right dataframe is filtered

---

packages/vaex-core/vaex/dataframe.py
tests/limits_test.py

This fixes #44. 
_Description:_
The selection seems to be ignored when calculating limits that are not `minmax`. For `minmax` the selection is obeyed, as shown by already implemented tests, and via manual testing.
```
limits = df.limits('x', value='90%', sel='x>5')  # selection is ignored
```
However, calculating limits on a filtered DataFrame gives the correct result:
```
df2 = df[df.x > 5]
limits = df2.limit('x', value='90%')  # give the correct result
```
_Checklist:_

Fix: limits calculation with selection

---

CHANGELOG.md
packages/vaex-core/vaex/expression.py
packages/vaex-meta/setup.py
packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-ml/vaex/ml/_version.py
packages/vaex-ml/vaex/ml/transformations.py
tests/ml/ml_test.py

Adding a `vaex.ml.GroupByTransformer`. This transformer creates aggregation of features just like a `groupby` operation which are then added to a DataFrame. With the `.transform` method, the same aggregations can be added to different DataFrames (e.g. validation, test sets).
This is useful for creating aggregate features useful for certain ML tasks.

Adding a GroupByTransformer in vaex.ml

---

packages/vaex-core/vaex/functions.py
tests/datetime_test.py

As suggested by #842, this PR adds  the `.floor()` datetime method.
The usage is as shown in the picture below:

Feature: adding `dt.floor()` method

---

packages/vaex-core/vaex/dataframe.py
tests/percentile_approx_test.py

Making the `percentile_approx` work with the 0th and 100th percentile.
Checklist:

Improvement: percentile_approx should work with the 0th and 100th percentile

---

packages/vaex-ml/vaex/ml/transformations.py
tests/ml/ml_test.py

This PR fixes an issue with the `WeightOfEvidence` encoder, that happens when a feature has no positive targets (binary classification case). 
Note: the case when a feature has no negative targets was already handled in the initial implementation. The same approach is used here for the other edge case.

fix(ml): weight of evidence encoder can handle edge cases

---

packages/vaex-core/vaex/expresso.py
tests/expresso_test.py

This PR fixes the issue that sometimes happens when chaining certain type of arithmetic operations. The issue is exposed via a unit-test.
Checklist:

Fix(core): not all operators where supported in expresso

---

tests/dropinf_test.py

I have forgotten to commit the unit-test during the implementation of `.dropinf()`  #821, so here it is now.

Add unit-test for dropinf

---

packages/vaex-core/vaex/dataframe.py
tests/percentile_approx_test.py

Small fix for `.percentile_approx` when the precentages include values like 0 or 100.

Fix: .percentile_approx endpoints

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-ml/vaex/ml/transformations.py
tests/agg_test.py

This PR enables the `df.minmax()` method to be applied on multiple expressions of different numeric types (e.g. int, float) at the same time.
Checklist:

Fix: minmax method for different dtypes

---

packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-ml/vaex/ml/transformations.py
tests/ml/ml_test.py

This is an out-of-core implementation of KBinsDiscretizer. 
It helps to create discretized out of continuous features is a nice and elegant way. Plays very well with GroupByTransformer as well. 
Ofc, fully compatible with the state transfer concept of vaex.
Here is an example:

New feature: KBinsDiscretizer

---

packages/vaex-ml/vaex/ml/catboost.py
tests/ml/catboost_test.py

Added four new params to *CatBoostModel*.
* **batch_size** - If provided, train in batches of that size.
* **batch_weights** - If provided and *batch_size* is provided, used to sum the models trained in batches and their feature importance. 
* **evals_result_** - Saving evals_result_ for all batches during training as the [sum_models](https://catboost.ai/docs/concepts/python-reference_sum_models.html) ignores it.
Implemented *get_feature_importance* to match the [Catboost method](https://catboost.ai/docs/concepts/python-reference_catboost_get_feature_importance.html).
Added feature_names to the data Pool such that the Catboost booster acknowledges the feature names.
Note - 
I designed it to run differently on a single run vs batch instead of a "cleaner" single batch version if batch_size …

Feature: batch training for Catboost

---

CHANGELOG.md
packages/vaex-core/vaex/dataframe.py
tests/dropna_test.py

This PR addresses a rather exotic case when the `repr` breaks when one drops NA, then filteres the dataframe, then drops NA on some different columns again. See unit-test for details.
Checklist:

Fix: multiple dropna() was using cached length

---

examples/vaexclient.py

@maartenbreddels Your review, please.
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.

Use print() function in both Python 2 and Python 3

---

.github/workflows/pythonpackage.yml
.travis.yml
appveyor.yml
ci/01-setup-conda.sh
ci/02-create-vaex-dev-env.sh
ci/03-install-vaex.sh
ci/04-run-test-suite.sh
ci/05-run-notebooks.sh
ci/conda-env-nightlies.yml
ci/conda-env-notebooks.yml
ci/conda-env.yml
ci/docker-test.sh
ci/runs-in-docker.sh
packages/vaex-server/vaex/server/tornado_server.py
tests/agg_test.py
tests/common.py
tests/execution_test.py
tests/graphql_test.py
tests/ml/ml_test.py
tests/percentile_approx_test.py

This should make it easier to reproduce locally a CI run using
`./ci/docker-test.sh` (we could polish this further with docker compose if needed).
Which is now using a series of bash script `ci/XX-blabla.sh` to execute the several stages.

Chore: ci refactor

---

docs/source/example_ml_iris.ipynb
packages/vaex-ml/vaex/ml/sklearn.py
tests/ml/sklearn_test.py

Requested in #920 .
This PR adds support for obtaining probabilities and log probabilities from sklearn classifiers. 
The `Predictor` and `IncrementalPredictor` classes now have a `prediction_type` kwarg, which can be set to `predict` (default), `predict_proba` and `predict_log_proba`. Each option will trigger the appropriate method in the sklearn classifier at prediction time.
Note: in this PR we are also removing a deprecated class (`vaex.ml.sklearn.SKLearnPredictor`), as it's deprecation period has expired. 
Checklist:

Feat(ml): Support for `predict_proba` and `predict_log_proba` for sklearn classifiers

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/file/__init__.py
packages/vaex-core/vaex/file/gcs.py
packages/vaex-hdf5/setup.py
packages/vaex-hdf5/vaex/hdf5/dataset.py
tests/gcs_test.py

This PR enables the streaming of HDF5 files directly from Google cloud storage. 
Vaex could already do this from S3, now we bring support for GCS as well. 
The usage is the same:
```
import vaex
df = vaex.open('gs://vaex-data/testing/xys.hdf5?cache=false&token=anon')
```
Note the slight differences compared to reading from S3. For reading data from GCP we are currently using `gcsfs` so the url parameters should be compatible with `gcsfs.GCSFileSystem`

Feat: stream hdf5 files directly from GCS

---

.github/workflows/pythonpackage.yml
CHANGELOG.md
packages/vaex-ml/MANIFEST.in
packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-ml/vaex/ml/_version.py
packages/vaex-ml/vaex/ml/catboost.py
packages/vaex-ml/vaex/ml/generate.py
packages/vaex-ml/vaex/ml/lightgbm.py
packages/vaex-ml/vaex/ml/sklearn.py
packages/vaex-ml/vaex/ml/spec.json
packages/vaex-ml/vaex/ml/spec.py
packages/vaex-ml/vaex/ml/transformations.py
packages/vaex-ml/vaex/ml/xgboost.py
tests/ml/catboost_test.py
tests/ml/lightgbm_test.py
tests/ml/ml_test.py
tests/ml/sklearn_test.py
tests/ml/xgboost_test.py

This is a way we can autogenerate the API.
There was an issue with this before, that in order the autogenerate the API, we had to import all packages, which is slow.
Instead, we now generate a spec:
```
$ python -m vaex.ml.spec packages/vaex-ml/vaex/ml/spec.json
```
Which allows us to build the API at runtime.
The spec also will allow us to track spec changes in the models, with CI helping us detect changes.
TODO:

feat: autogenerate fast api

---

packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-ml/vaex/ml/transformations.py
tests/arrow/assumptions_test.py
tests/ml/ml_test.py
tests/unique_test.py

This addresses  an issue of `.unique` when applied on a string column that has missing value.
I am not completely sure, but fixing this might fix #879 
Checklist

Fix: unique on str column that has missing values

---

packages/vaex-core/vaex/dataframe.py
tests/ipython_test.py

Adding tab competion when accessing columns using the dictionary syntax.
example:
`df['hom' (tab)]` -> `df['home_dest']`

Feature: adding ipython tab-completion

---

ci/conda-env.yml

See https://github.com/vaexio/vaex/issues/976

chore(ci): pytest-asyncio 0.14 breaks tests/process_test test_progress_calls_async

---

CHANGELOG.md
packages/vaex-core/vaex/expresso.py
tests/expresso_test.py

This was a too strict test, since we allow Unicode column names

fix(core): allow unicode variable names in expressions, fixes #949

---

packages/vaex-core/vaex/__init__.py
tests/from_pandas_test.py
tests/repr_test.py

Enable `vaex.from_pandas()` to recognize the new `pandas.StringDtype` (or "string" for short when using it in pandas).
Also, update the test to cover these cases.
Checklist:

Feat: recognize pandas "string" dtype

---

packages/vaex-core/vaex/functions.py
tests/datetime_test.py

Fix: property cast dt_strftime to string type

---

.gitignore
packages/vaex-core/vaex/arrow/numpy_dispatch.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/encoding.py
packages/vaex-core/vaex/export.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/formatting.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/scopes.py
packages/vaex-core/vaex/selections.py
packages/vaex-core/vaex/utils.py
packages/vaex-hdf5/vaex/hdf5/export.py
tests/arrow/compute_test.py
tests/astype_test.py
tests/common.py
tests/dtypes_test.py
tests/evaluate_test.py
tests/materialize_test.py
tests/rename_test.py
tests/values_test.py

A proof of concept that we can wrap Arrow arrays to dispatch calculations to Numpy.
The main point of this is that we can work towards running the full test suite in an
Arrow backed dataframe. We can gradually remove them over time when Arrow gets more
compute kernels.

feat(core): dispatch compute on arrow arrays to numpy

---

.github/workflows/pythonpackage.yml
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/hash.py
tests/value_counts_test.py

This PR handles the issue of doing value counts on a virtual column which is created by adding or concatenating strings.

Fix: value counts on added/concatenated strings

---

packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/groupby.py
tests/agg_test.py

This PR fixes some issues with the groupby aggregators, when the `selection` kwarg is used.
Case 1:
the selection is ignored when the `==` operator is used with a float or int. Ex.  `vaex.agg.count(selection=df.x == 1)`. This will give the same result as if `selection=None`.
Case 2:
If a selection of an aggregation is such that no data is left, the entire row (group) is removed from the resulting grouped DataFrame (see unit-test for details). 
AC:

Fix: groupby aggregators return incorrect output for certain selections

---

tests/isin_test.py

This test uncovers a bug in `.isin` method: if a column is string, and has `None` values inside, `.isin` will return `False` for all samples.

Bug in .isin() for string columns that have None

---

.github/workflows/pythonpackage.yml
CHANGELOG.md
packages/vaex-astro/vaex/astro/transformations.py
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/arrow/dataset.py
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/dataset.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/expresso.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/multithreading.py
packages/vaex-core/vaex/test/dataset.py
tests/agg_test.py
tests/common.py
tests/copy_test.py
tests/dataset_test.py
tests/drop_test.py
tests/expression_variables_test.py
tests/expresso_test.py
tests/join_test.py
tests/slice_test.py

This PR includes all refactors such that we can leverage Arrows Dataset API. This allows out of core dataframe backed by a parquet file. In principle goodies such as s3 support should work, but I haven't tried it yet.
Demo:
I think it's a bit on the slow side, for e.g. a single column, compared to sub 100ms for a memory mapped hdf5 or arrow file. But for slow storage/network this will speed up things quite a bit.

Feat: Out of core Parquet support using Arrow Dataset scanning

---

ci/conda-env.yml
packages/vaex-ml/vaex/ml/lightgbm.py
packages/vaex-ml/vaex/ml/spec.json
tests/ml/lightgbm_test.py

This PR allows safely usage of the lightgbm wrapper through vaex.ml for the latest version(s) of lightgbm (>=3.0.0).
Vaex.ml implemented a special `VaexDataset` class built on top of the `lightgbm.Dataset` class, and allowed for more memory efficient way of passing vaex data to lightgbm. This came at some performance penalty. 
Lightgbm 3.0.0 introduced breaking changes to their Dataset. We do not currently have the capacity to maintain the `VaexDataset`, so it is best to remove it for now. If anybody in the community is willing to pick this up, they are welcome to.

Chore: LightGBM wrapper cleanup

---

packages/vaex-core/vaex/utils.py

When using vaex with a multiprocessing library, or gunicorn with multiple gunicorn workers, the above condition fails sometimes. ( race condition between workers)
With this change, os.makedirs will fail silently if the directory already exists.
Please find the stacktrace below, this is a random behaviour i have seen.
```
File "/app/dataframe_reader/minio_utils.py", line 19, in <module>
from vaex_arrow.convert import column_from_arrow_array, vaex_df_from_arrow_table
File "/usr/local/lib/python3.6/site-packages/vaex_arrow/convert.py", line 4, in <module>
from vaex.column import ColumnStringArrow
File "/usr/local/lib/python3.6/site-packages/vaex/__init__.py", line 49, in <module>
import vaex.datasets
File "/usr/local/lib/python3.6/site-packages/vaex/datasets.py", line 7, in <module>
data_dir …
```

Update os.makedirs to use a exist_ok flag

---

.github/workflows/pythonpackage.yml
packages/vaex-ml/vaex/ml/sklearn.py
packages/vaex-ml/vaex/ml/spec.json

As the title says, this PR changes the default value from `''` to `None` in `vaex.ml.sklearn.Predictor`.
This was motivated by #1004 . While the `vaex.ml.sklearn.Predictor` class is not meant to be used for sklearn classes that are not estimators/predictors (i.e. classes that do not implement the `.predict` method) , which change gives a bit better user experience. 
N.B: This is not a breaking chance.

Change default value from `''` to `None` in vaex.ml.sklearn.Predictor

---

packages/vaex-core/vaex/arrow/dataset.py
packages/vaex-core/vaex/dataset.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/itertools.py
packages/vaex-core/vaex/multithreading.py
tests/dataset_test.py

This makes it easier to implement streaming input, and with
this new implementation the parquet reading is about 3x faster.
Compared to https://github.com/vaexio/vaex/pull/993 where it took 3 seconds to go over a single columns, it is now subsecond.

refactor: dataset API returns chunks instead of callable (3x faster parquet reading 🔥)

---

ci/04-run-test-suite.sh
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/datatype.py
packages/vaex-core/vaex/datatype_test.py
packages/vaex-core/vaex/encoding.py
packages/vaex-core/vaex/export.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/file/__init__.py
packages/vaex-core/vaex/tasks.py
packages/vaex-core/vaex/utils.py
packages/vaex-hdf5/vaex/hdf5/export.py
tests/dtypes_test.py
tests/strings_test.py

See the docstring of datatype.py for usage.
We should decide if we want this or not, and if so, we need to put this also in the docs:
TODO:
* Add `py.test --doctest-modules packages/vaex-core/vaex/datatype.py` to CI
* add `packages/vaex-core/vaex/datatype_test.py` to CI
* Review naming

refactor!: Vaex DType wraps NumPy and Arrow DType in uniform way

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataset_mmap.py

Use `df.close_files()` instead of `df.close()` to ensure the file lock on hdf5 chunks gets released and hence can be deleted.

Fix deletion of chunk files on csv->hdf5 conversion

---

ci/04-run-test-suite.sh
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/export.py
packages/vaex-core/vaex/test/dataset.py
packages/vaex-core/vaex/utils.py
tests/common.py
tests/server/performance_test.py

Now the maximum chunk_size is the old default (1024^2).
For smaller datasets, it will choose a chunk_size such that
each thread will get some work to do, unless smaller than
chunk_size_min_default which is set to 1024 by default.
TLDR, chunk_size will be between 1024 and 1024^2 from now on.
This can be configured with env var:
VAEX_CHUNK_SIZE_MIN=10
VAEX_CHUNK_SIZE_MAX=100000
A fixed, default chunk_size can also be set using:
VAEX_CHUNK_SIZE=123456

feat: determine default chunk_size for smaller datasets

---

ci/conda-env.yml
packages/vaex-core/vaex/arrow/numpy_dispatch.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/scopes.py
packages/vaex-core/vaex/stat.py
tests/common.py
tests/compute_test.py
tests/viz_test.py

We can also mix numpy masked arrays and arrow arrays without losing missing values.

fix: dispatching computations to numpy was missing null/missing support

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/arrow/dataset.py
packages/vaex-core/vaex/cache.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/file/__init__.py
packages/vaex-core/vaex/file/cache.py
packages/vaex-core/vaex/file/column.py
packages/vaex-core/vaex/file/gcs.py
packages/vaex-core/vaex/file/s3.py
packages/vaex-core/vaex/file/s3arrow.py
packages/vaex-core/vaex/file/s3fs.py
packages/vaex-hdf5/vaex/hdf5/dataset.py
tests/file_test.py

See https://issues.apache.org/jira/browse/ARROW-10709
When we use the CPP layer FileSystem, in combination with caching, we
get hit hard by memory copying/GIL (5x slower!).
When we know we don't pass the filesystem to CPP land, we can skip that
layer and avoid memory copies.
In the future, we can probably return a memoryview anyway based on the
Apache Arrow version number.
Effect, when reading hdf5 from cache: we go from 20 seconds down to 4.

perf: skip CPP layer of Apache Arrow when possible for performance

---

packages/vaex-core/vaex/execution.py

Related #1074 
confirmed it's working by running in a 1GB docker container:
```python
import vaex
import numpy as np
N = 1024*1024//8*500
x = np.ones(N)
df = vaex.from_arrays(x=x)
df['y'] = df.x*2
print(df.y.sum())
```
this will crash
`$ VAEX_CHUNK_SIZE=10000000 python /home/maartenbreddels/github/vaexio/vaex/memusage.py`
this will not
`$ VAEX_CHUNK_SIZE=10000 python /home/maartenbreddels/github/vaexio/vaex/memusage.py`

fix: chunk_size was ignored

---

docs/source/conf.py
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/docstrings.py

This PR hope to achieve two things:
- Improve the docstring of `vaex.open(...)`
- Refactor a bit how we generate the docstrings for common keywords.
- Remove `copy_index` from `vaex.open`. This kwarg is not general, but only applies when a csv file is read via `pandas.read_csv`. It can still be passed as part of the `**kwargs` so there is no loss of functionality here, and old code will **not** break.
Checklist

Improve vaex.open docstrings

---

packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/dataframe.py
tests/evaluate_test.py

This was exposed since we now calculate a dynamics chunk_size.
Also, because of a wrong dtype check, we lost performance due to
unneeded array copies going on.
Test now covers all cases.
Fixes #1083

fix: evaluate would sometimes return an array of list of arrays

---

packages/vaex-core/setup.py
packages/vaex-core/src/agg_hash_primitive.cpp
packages/vaex-core/src/hash.hpp
packages/vaex-core/src/hash_primitives.cpp
packages/vaex-core/src/hash_primitives.hpp
packages/vaex-core/src/hash_primitives_pot.cpp
packages/vaex-core/src/hash_primitives_prime.cpp
packages/vaex-core/src/superutils.cpp
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/hash.py

With particular data, we mean data (primotives) for which the lower
bits don't change much.
See https://tessil.github.io/hopscotch-map/#growth-policy
In those cases (since we use an identify hash function), it is better
to have a prime growth strategy.
Also, based on the cardinality, we use less hash maps.

feat: join improvements for high cardinality data and particular data.

---

packages/vaex-core/vaex/file/s3arrow.py
packages/vaex-core/vaex/file/s3fs.py

For some reason, if we request many files, and request the region
many times, curl (underlying arrow) fails to resolve the DNS name.
In any case, it makes sense to cache regions and filesystem objects.
Fixes #1084

fix: cache filesystem object to avoid #1084

---

packages/vaex-core/vaex/__main__.py
packages/vaex-core/vaex/file/__init__.py

When converting many files in parallel (Gaia data), sometimes a process gets killed and leaves an invalid file, with 60 000 files that is difficult to recover from using command line utils, with a command like:
```
find . -iname '*csv.gz' | sed 's/gz/hdf5/' | xargs -P32 -n32 vaex open --delete
```
We can detect invalid files and remove them.
Also cleaned up the help a bit.

feat: vaex open cmd line util to check and/or delete invalid files

---

packages/vaex-core/src/agg.hpp
packages/vaex-core/src/agg_hash_primitive.cpp
packages/vaex-core/src/agg_hash_string.cpp
packages/vaex-core/src/superagg.cpp
packages/vaex-core/src/superagg_binners.cpp
packages/vaex-core/vaex/arrow/dataset.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/dataset.py
packages/vaex-core/vaex/file/__init__.py
packages/vaex-server/vaex/server/client.py
packages/vaex-server/vaex/server/dataframe.py
packages/vaex-server/vaex/server/tornado_client.py
tests/pickle_test.py

Note that this not means you get free distributed computing, but it's possible to very efficiently pass around a vaex dataframes in Dask, Ray or multiprocessing (which use pickle).
Pickling `hdf5`, `parquet` and 'arrow ipc' backed dataframes pass the file path around, which means it is quite fast. CSV backed files currently pass around the data, which is slower (This will change).
```
$ dask-scheduler --host localhost
$ VAEX_NUM_THREADS=16 dask-worker localhost:8786 --nthreads=1 --nprocs=2 --memory-limit=100G
```
Dask complains about memory usage, but that's all memory mapped memory it is reading, so we pass `--memory-limit=100G`.
```python
import dask
import vaex
from dask.distributed import Client
client = Client('127.0.0.1:8786')
@dask.delayed
def partial_sum(df):
sub_total = …
```

feat: DataFrame pickle support for Dask, Ray and multiprocessing.

---

ci/conda-env.yml
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/arrow/convert.py
packages/vaex-core/vaex/arrow/dataset.py
packages/vaex-core/vaex/arrow/opener.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/file/__init__.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/groupby.py
tests/arrow/convert_test.py
tests/arrow/partitioned_test.py
tests/groupby_test.py

Fixes #834
Similar to groupby, we can write those partitions to disk:
```python
import vaex
countries = ['US', 'US', 'NL', 'FR', 'NL', 'NL']
years = [2020, 2021, 2020, 2020, 2019, 2020]
values = [1, 2, 3, 4, 5, 6]
df = vaex.from_dict({
'country': countries,
'year': years,
'value': values,
})
df.export_partitioned('./partitioned', by=['country', 'year'])
```
```
$ ls -R ./partitioned/
./partitioned/:
'country=FR'  'country=NL'  'country=US'
'./partitioned/country=FR':
'year=2020'
'./partitioned/country=FR/year=2020':
c543a46a-8188-4a0d-bd97-609c2adea36f.parquet
'./partitioned/country=NL':
'year=2019'  'year=2020'
'./partitioned/country=NL/year=2019':
545776eb-16dc-46d6-9882-fd68114b42be.parquet
'./partitioned/country=NL/year=2020':
c4211f02-10ef-499c-9175-5ffbcd274770.parquet …
```

feat: Hive based partitioned datasets support. Read parquet, write any

---

.github/workflows/pythonpackage.yml
appveyor.yml
packages/vaex-core/vaex/functions.py
tests/timedelta_test.py

It seems pandas 1.2 eagerly converts to dtype=object, e.g.:
```
delta = np.array([17658720110, 11047049384039, 40712636304958, -18161254954], dtype='timedelta64[s]')
pdf = pd.DataFrame({'delta': delta})
pdf.delta.dtype == 'O'
```
I couldn't find this in the pandas issues (cc @jorisvandenbossche)

fix: support for use with pandas 1.2

---

packages/vaex-core/vaex/column.py
tests/column_test.py

Fixes #1001 closes #1031
I generated a test case (and fix, obviously 😄)that fails for the latest vaex version:
```
'vaex': '4.0.0a7',
'vaex-core': '4.0.0a12',
'vaex-viz': '0.5.0.dev1',
'vaex-hdf5': '0.7.0a5',
'vaex-server': '0.4.0a1',
'vaex-astro': '0.8.0.dev1',
'vaex-jupyter': '0.6.0.dev1',
'vaex-ml': '0.11.0a4'
```
The issue is caused by all indices being masked, which I force by attempting a join where there are no identical join keys. I added a test case that will fail should the issue still persist.
Let me know if you need anything else from me!
Edit: Apologies if the test case is in the wrong place. I'm not sure where you build server tries to load the test files.

fix: ColumnIndexed slice issue when all indices are masked

---

packages/vaex-astro/vaex/astro/fits.py
packages/vaex-astro/vaex/astro/gadget.py
packages/vaex-astro/vaex/astro/votable.py
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/arrow/dataset.py
packages/vaex-core/vaex/cache.py
packages/vaex-core/vaex/convert.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/dataset.py
packages/vaex-core/vaex/docstrings.py
packages/vaex-core/vaex/file/__init__.py
packages/vaex-core/vaex/utils.py
packages/vaex-hdf5/vaex/hdf5/dataset.py
tests/file_test.py

Instead of us creating the filesystem, we let uses create it, and pass
it down to vaex.
Example:
```python
import vaex
import fsspec
fs = fsspec.filesystem('https')
vaex.open('https://github.com/vaexio/vaex-datasets/releases/download/v1.0/helmi-dezeeuw-2000-FeH-v2-10percent.hdf5',
fs=fs)
```

feat: support fsspec and arrow filesystem by passing around fs argument

---

packages/vaex-core/setup.py
packages/vaex-core/vaex/arrow/opener.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/docstrings.py
tests/cloud_dataset_test.py

So this PR is part suggestion and part question 😄 
I recently put together a [comparison of vaex and kdb+ for finance type analyses](https://www.aquaq.co.uk/q/comparing-columnar-data-formats-arrow-vaex-and-kdb/) - vaex comes out pretty well considering the difference is maturity - and one of the more important features vaex is currently lacking for this kind of workload is compression.  
[Feather (v2)](https://ursalabs.org/blog/2020-feather-v2/) adds compression support to arrow files, but otherwise files saved as feather seem identical to the arrow IPC format, and so work identically when opened in vaex (or appear to do so).  I've added a simple `export_feather` function here that allows for saving compressed arrow files.  So far as I can tell feather is currently the only way to do this …

feat: add export_feather function to allow compressed arrow files

---

packages/vaex-core/vaex/groupby.py

A for loop in GroupBy is unnecessarily duplicated

chore: Remove duplicate for loop in GroupBy

---

packages/vaex-astro/vaex/astro/fits.py

Hello! I found a small typo that was causing an error when reading in FITS tables with `TUNITn` header keywords.

Fix typo in _get_column_meta_data function

---

packages/vaex-core/vaex/dataframe.py
tests/execution_test.py

Because self.local._aggregator_nest_count is set from the calling thread
and the thread doing the execution may not have set the _aggregator_nest_count
attributes, we could get the following exception:
```
>       self.local._aggregator_nest_count += 1
E       AttributeError: '_thread._local' object has no attribute '_aggregator_nest_count'
```

fix: allow executor to be in a different thread

---

packages/vaex-core/vaex/arrow/numpy_dispatch.py
packages/vaex-core/vaex/arrow/utils.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
tests/agg_test.py

Example
```python
data = [1, 2, None], None, [], [1, 3, 4, 5]
df = vaex.from_arrays(i=pa.array(data).slice(offset))
assert df.i.sum() == [16, 13][offset]
assert df.i.sum(axis=1).tolist() == [3, None, 0, 13]
assert df.i.sum(axis=1, fill_missing=99).tolist() == [3, 99, 0, 13]
assert df.i.sum(axis=1, fill_missing_item=10).tolist() == [13, None, 0, 13]
assert df.i.sum(axis=1, fill_empty=10).tolist() == [3, None, 10, 13]
assert df.i.sum(axis=[0, 1]) == [16, 13][offset]
```

feat: sum over list

---

ci/conda-env-nightlies.yml
packages/vaex-core/setup.py
packages/vaex-core/src/strings.cpp
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/arrow/convert.py
packages/vaex-core/vaex/arrow/utils.py
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/functions.py
tests/compute_test.py
tests/strings_test.py

We should support the string features that are ported to Apache Arrow v3, which should be released soon
* ~~[ ] trim https://github.com/apache/arrow/pull/8621~~

String features for use with Apache Arrow v3.0

---

packages/vaex-core/vaex/arrow/numpy_dispatch.py
tests/datetime_test.py
tests/fillna_test.py

In the case of ColumnStringArrow, NumpyDispatch was converting to a PyArrow array but then not doing anything with it. Instead, it needed to updated the object's `_array` attribute.

fix: NumpyDispatch with ColumnStringArrow

---

docs/source/installing.rst

On Windows, the local/developer installation needs administrator privileges to succeed

fix (docs): Windows developer install needs admin privileges

---

packages/vaex-core/vaex/__init__.py
tests/from_pandas_test.py

This PR allows vaex to parse the `Float64Dtype()` from pandas, which allows for masked values (also works for 32bits).

Feat: allow parsing of the FloatDtypes() from pandas

---

packages/vaex-core/vaex/file/__init__.py
packages/vaex-core/vaex/file/cache.py
tests/state_test.py

This PR irons out the support for loading state files from cloud storage. 
To do:

Fix: Support for loading state files from GCS

---

ci/conda-env.yml
packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-ml/vaex/ml/generate.py
packages/vaex-ml/vaex/ml/spec.json
packages/vaex-ml/vaex/ml/transformations.py
tests/ml/conftest.py
tests/ml/ml_test.py
tests/ml/ui_test.py

This essentially provides a vaex-ified wrapper around `sklearn.decomposition.IncrementalPCA`. 
The sklearn transformer is only used for fitting the pca model (getting the eigen-values and eigen-vectors with their incremental algorithm). 
The transformation and overall behavior/usage is identical to what is currently available in `vaex.ml.PCA`. 
_Note:_ we opted for `PCAIncremental` over `IncrementalPCA` (scikit-learn) so that the auto-complete feature in IDEs will naturally "group" these transformers. 
**Reason for this feature:**
Due to the differences in their implementation, both Transformers can be very fast on different types of data (shapes):
- `vaex.ml.PCA` shines for "tall" dataframes (many rows, few columns).
- `vaex.ml.PCAIncremental` shines for "wide" dataframes (many columns). …

Feat: `vaex.ml.PCAIncremental`

---

packages/vaex-core/vaex/dataframe.py

Without the added `df =` the second line of the example did nothing.
Showing that the representation doesn't change but `is_category` will now reveal
that the dataframe knows a column has a categorical dtype also seems useful.

doc: extend the df.categorize example

---

ci/conda-env.yml
packages/vaex-core/vaex/utils.py
packages/vaex-ml/vaex/ml/__init__.py
packages/vaex-ml/vaex/ml/spec.json
packages/vaex-ml/vaex/ml/transformations.py
tests/ml/ml_test.py

This PR implements the `RandomProjections` method for dimensional reduction. 
It uses the methods in scikit-learn for creating the random matrices, so scikit-learn is needed as a dependency of using this transformer.  Scikit-learn is however not needed to apply the transformations of an already fitted transformer.

RandomProjections implementation

---

packages/vaex-ml/vaex/ml/incubator/river.py
packages/vaex-ml/vaex/ml/spec.json
packages/vaex-ml/vaex/ml/spec.py
packages/vaex-ml/vaex/ml/spec_new.json
tests/ml/river_test.py

This PR provides a convenient wrapper around models and even pipelines of [River](https://github.com/online-ml/river).
The requirement is that the models implement the `learn_many` method, and currently it is assumed that the `predict_many` method returns a pandas Series. 
For the reason / motivation behind this, please see https://github.com/online-ml/river/discussions/515.
With the wrapper, the River models become part of the vaex computational graph, and one gets full benefit of the serialization and lazy evaluation. 
Here is a basic example:
```python
import vaex
import vaex.ml
from vaex.ml.incubator.river import RiverModel
from river.linear_model import LinearRegression
from river import optim
df = vaex.example()
df_train, df_test = df.ml.train_test_split(test_size=0.2, …
```

River integration

---

packages/vaex-core/vaex/dataset.py
tests/dataset_test.py
tests/rename_test.py

🐎 avoid nested renaming for dataset, and collapse in single operation

---

packages/vaex-core/src/strings.cpp
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
tests/isin_test.py

- Fixes #1320 at the Python level; technically, the bug is caused at the C++ level when the `set.isin()` function implicitly downcasts its own values to the same type as the value its comparing against; ex: input column is a float and `isin([1])` is called (1 is an int) --> all floats are downcasted/rounded down to the nearest int and can return incorrect results
- One test case/assert isolates a potential C++ bug but I was not able to fix it at this time; more details are below
Currently, one assert case fails for a masked string column when `use_hashmap = False`. Specifically, I believe there is a bug at the C++ level when a masked string column's `<string_column>.string_sequence.isin()` function is called. There are no issues when `use_hashmap = True` as evident by an earlier assert in …

🐛Fix isin() dtype downcasting and use_hashmap=False

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/groupby.py
tests/groupby_test.py

The default is not to sort, which is faster, while pandas does sort by default.
There is a pre_sort present in the grouper, which should be faster by default, but for symmetry with the GrouperCategory which cannot do that, the parameter is added.

✨ sorted groupby result

---

packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/scopes.py
tests/column_names_test.py

cc @antoinerg who got bitten by a column called 'float', this now works:
```python
import vaex
import os
with open("data.csv", "w") as fd:
fd.write("id,float\n0,7.5\n1,8.5\n")
df = vaex.from_csv('data.csv')
print(df["float"].nunique())
df
```

🐛 column names equal to function names

---

packages/vaex-astro/vaex/astro/votable.py

There was a typo - a print call with a string an immediately after that the arguments to be inserted without the percent sign

Corrected typo - missing % in formatting string

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/utils.py
tests/groupby_test.py
tests/internal/groupby_test.py

```python
import numpy as np
import vaex
n = 10_000
x = np.random.rand(n)
y = np.random.rand(n)
z = np.random.rand(n)
df = vaex.from_arrays(x=x, y=y, z=z)
```
before:
```python
%%time
dfg = df.groupby(['x', 'y'], agg=vaex.agg.sum('z'))
#CPU times: user 4.16 s, sys: 5.94 s, total: 10.1 s
#Wall time: 10.1 s
```
after:
```python
%%time
dfg = df.groupby(['x', 'y'], agg=vaex.agg.sum('z'))
```
which is about ~250 times faster. A lot of time was wasted on allocating memory as well.
There are situations where this is slower, so we may want to release this with `assume_sparse=False` first.
cc @nicolaskruchten

🐎 perform groupby in a sparse way for less memory usage/performance (~250 times faster)

---

packages/vaex-core/vaex/__init__.py

I've done the minimal intervention necessary to comply with the issue, as raised. However, the [consistent logging issue in a library](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) might be a more involved discussion, and possibly requiring architecture input from you... 
* The VAEX logging will happen through the named logger object.
* The formatter applies to the named logger instead of the root one.
* Switched the obsolete FATAL loglevel to ERROR
Fixes vaexio/vaex#1366

🐛 Apply formatting to named logger

---

packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/datatype.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/scopes.py
packages/vaex-core/vaex/tasks.py
tests/agg_test.py
tests/category_test.py
tests/common.py
tests/groupby_test.py
tests/unique_test.py

It should just work as if a dataframe after df.ordinal_encode is the
same (so unique gives the same results etc). The only thing that should
be different is the performance.

🔨 categorical data should hide that it is dict/ordinal encode

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/groupby.py
tests/common.py
tests/groupby_test.py
tests/internal/hash_test.py

This can be useful if you only want to do a groupby when the result
is small and otherwise don't care about the result.
cc @nicolaskruchten
See usage:

✨ limit rows in groupby using early stop.

---

.github/workflows/pythonpackage.yml
appveyor.yml
docs/source/api.rst
packages/vaex-astro/vaex/astro/gadget.py
packages/vaex-astro/vaex/astro/votable.py
packages/vaex-core/src/hash_object.cpp
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/cache.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/encoding.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/tasks.py
tests/cache_test.py
tests/common.py
tests/conftest.py
tests/copy_test.py
tests/execution_test.py
tests/fingerprint_test.py
tests/internal/filecache_test.py
tests/jupyter/model_test.py
tests/jupyter/plot_widget_test.py
tests/progress_test.py

Since we can calculate fingerprints of almost all things in vaex now, we can start adding in global caching:
Note that only the first time we do the calculation, even after we open the dataframe again, and do the same calculation, we still find it in the cache (look at the timings), because the dataset fingerprint (and thus dataframe fingerprint) are the same.
This does not work yet for groupby, which is due to the sets in the variables dict that is modifying the input dataframe, which we should not do I think.
cc @nicolaskruchten @xdssio 
TODO:

✨ allow caching of tasks outputs

---

packages/vaex-core/vaex/datatype.py
packages/vaex-core/vaex/groupby.py
tests/cache_test.py
tests/groupby_test.py

before, this could take 1m50s: `df.groupby(['passenger_count', 'vendor_id'], sort=True, agg='count')`
Now takes 5 seconds

🐎 sparse groupby passed over original dataframe, this is faster

---

packages/vaex-core/vaex/asyncio.py

Simple fix to handle dev versions like 8.0.0.dev. Assume we only want the first 3 version bits.

Fix version compare when running development IPython which has versions like 8.0.0.dev. #1388

---

packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/shift.py
tests/shift_test.py

This contains fixes for various shift related issues:

Fixes for shift related methods

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/encoding.py
tests/drop_test.py

This is due to df._expr() not going through df[...] which corrects
invalid identifiers.

🐛 df.drop failed to find deps when the column was an invalid identifier

---

packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/dataframe.py
tests/category_test.py

Going ordinal encode on already numerical columns between `[0, N]` should use df.categorize, warn the user and take the categorize path.

🐎 running df.ordinal_encode can be replaced by df.categorize

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/test/dataset.py
tests/countna_test.py
tests/from_json_test.py
tests/groupby_test.py
tests/ml/ml_test.py
tests/rolling_test.py
tests/shift_test.py
tests/timedelta_test.py
tests/to_test.py

By telling pandas the dtype should be string and asking it to convert
back using arrow, we avoid multiple issues, and it's probably faster.
Closes #1455

🐛 Expression.str_pandas resulted in nans for Pandas >=1.3

---

packages/vaex-core/vaex/dataframe.py
tests/nop_test.py

This fix was raised by https://github.com/vaexio/dash-120million-taxi-app/issues/3

Allow dataframe.nop to accept both a single and a list of expressions

---

packages/vaex-core/vaex/dataframe.py
tests/concat_test.py

Hi, this is my first PR to vaex.
This solves the issues raised in:  #1361
I want to fix vaex so that concat will succeed even if the name of the virtual column exists on one side and the column with that name does not exist on the other side. 
For example,
```python
df1 = vaex.from_arrays(x=np.arange(3))
df2 = vaex.from_arrays(x=np.arange(3))
df1['z'] = df1.x ** 2
df = df1.concat(df2)
```
In above example, df1 is
| # | x |  z
| ---- | ---- | ---- | 
| 0 | 0  |  0  |
| 1 |  1  |  1  | 
| 2 |  2  | 4  |
df2 is 
| # | x |  
| ---- | ---- | 
| 0| 0  |  
| 1|  1  |  
| 2|  2  |  
so, I expected df will be
| # | x |  z
| ---- | ---- | ---- | 
| 0  | 0  |  0  |
| 1 |  1  |  1  | 
| 2 |  2  | 4  |
| 3 | 0  |  --  |   
| 4 |  1  | -- |   
| 5 |  2  | -- |  
but, it ends in  KeyError: "Virtual …

concat with the virtual column when not exist in the other dataframe

---

packages/vaex-astro/vaex/astro/fits.py
packages/vaex-core/vaex/file/__init__.py

Caused CI to fail with the latest astropy (4.3), triggering:
```
OSError: No SIMPLE card found, this file does not appear to be a valid FITS file
```
Introduced in https://github.com/astropy/astropy/pull/10895

fix: astropy doesn't like left aligned data

---

packages/vaex-hdf5/vaex/hdf5/writer.py
tests/export_test.py

Hi👋
This solves the issues raised in: #1478 
In export_hdf5 method, the procedure **was** as follows. 
1. Create/Open hdf5 file (in init function at Writer class)  
2. Open mmap file (in layout method)
3. Close hdf5 file (in close method)
4. Close mmap (in close method)
I made a hypothesis that this procedure might be not a good in windows environment and I read vaex/h5py/hdf5 source code. I didn't found the bug logic on the h5py/hdf5 source, but I was able to reproduce this bug in small scripts without vaex. 
```python
import h5py
import mmap
path = "mytestfile.hdf5"
f = h5py.File(path, "w") # Open HDF5 File =================
file = open(path, "rb+")  # Open mmap file ------------------------
fileno = file.fileno()
cg = f.require_group("column")
kwargs = {}
kwargs["access"] = …
```

fix: export dataframe to hdf5 when it includes multibyte named column (on Windows OS) 

---

packages/vaex-ml/vaex/ml/tensorflow.py
tests/ml/tensorflow_test.py

This PR adds a simple class for serialization and lazy predictions of keras models. 
Please see the unit-test for details of intended use. In general it is quite similar to the rest of the model wrappers provided by vaex ML. The main difference is that the `fit` method is not implemented, so one is expected to fit the keras model via the `tensorflow.keras` API. This is done to maintain flexibility of having a wide spectrum of use-cases. 
This PR will be one of several smaller PRs that will eventually supersede #622, which was perhaps a bit of an ambitions step at the time.

feat(ml): Adding a simple class for serialization of Keras models

---

packages/vaex-core/vaex/dataframe.py

Params was lost as described here: https://github.com/vaexio/vaex/issues/1495

Adding writer params to hdf5 writer

---

packages/vaex-core/vaex/functions.py
tests/strings_test.py

This PR addresses issue #1154 and #1368 and is work in progress since there are conceptual questions remaining.
Adding a wrapper for apache arrows [`extract_regex`](https://arrow.apache.org/docs/cpp/compute.html#string-extraction) under the vaex dataframe string namespace is straightforward. However, handling the returned result is somewhat more complicated because it is not a single column of a primitive type but rather a collection of primitive types (StructArray in Arrow). There may be different valid approaches here which I would like to discuss with you before going any further (creating tests):
1. **Plain Arrow StructArray**: Just keep the standard arrow struct array and do not modify it any further. Arrow's struct arrays are currently not properly converted to dask/numpy within …

Add `str_extract_regex` to dataframe str function namespace.

---

docs/source/api.rst
docs/source/example_io.ipynb
docs/source/tutorial_ml.ipynb
packages/vaex-ml/vaex/ml/tensorflow.py

Small update to the documentation pages:
- Added the `struct` methods to the API documentation
- Added a `Keras` example to the documentation
- Added a simplified example in the docstrings of `ml.tensorflow.KerasModel`
- Fixed typo found by #1492 
To do: probably later on in a separate PR, we should update the main tutorial, or gave an additional page explaining the usage of the arrow `struct` types.

Docs: Keras + Struct docs

---

docs/source/api.rst
docs/source/tutorial_ml.ipynb
packages/vaex-ml/setup.py
packages/vaex-ml/vaex/ml/incubator/river.py
packages/vaex-ml/vaex/ml/metrics.py
tests/ml/metrics_test.py

New ml accessor, `metrics`. 
Allows for fast and out-of-core computation of some popular / common ML metrics for classification and regression.
Please see the tests, docstrings or the documentation  for examples.

ML metrics

---

packages/vaex-core/setup.py
packages/vaex-core/vaex/cache.py
packages/vaex-core/vaex/file/cache.py
tests/open_test.py

This shows up when multiple threads or processes try to do a conversion
or create a cache file.

🐛 protect file creation parts with lock files

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/utils.py

this avoids df['Invalid identifier'] entering df.data_type()
triggering an evaluation phase

🐎 avoid falling back to eval to get the dtype

---

packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/multithreading.py

If we had N threads, all throwing the same exception, N-1
warnings of un-awaited exceptions. We also always put the
exception in the log.

🐛 too much noise when exceptions occurred in the executor.

---

docs/source/api.rst
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/column.py
tests/column_test.py

This PR adds a vaex method to add virtual columns having constant values. 
The method is called `vaex.vconstant`
This was requested a few of times in the past, example #1019, #1557
This is how for instance one can create a fully virtual dataframe:
```python
import vaex
N = 100_000_000
df = vaex.from_arrays(x=vaex.vconstant(value=10, length=N),
y=vaex.vconstant(value='Vaex', length=N),
z=vaex.vrange(0, N)
)
```
Checklist:

feat(core): Method to add virtual columns having constant values.

---

packages/vaex-core/vaex/dataframe.py

When using states to perform prediction on a single datapoint, a lot of time was spent on deleting columns. Allowing it to be optional reduced the prediction time by 10% in my case.

Parameter to decide if drop columns or not while running state_set

---

packages/vaex-core/setup.py
packages/vaex-core/vaex/asyncio.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/execution.py
packages/vaex-server/vaex/server/client.py
packages/vaex-server/vaex/server/tornado_client.py
packages/vaex-server/vaex/server/websocket.py

This avoids the use of nest_asyncio, where we have instead of 'shared-nested' ioloops, we make 'new-nested' ioloops. This means that if we do a async->sync->async call, the deepest async code will pause the ioloop of the parent. Note that this not work with vaex-jupyter, because that requires the jupyter ioloop to continue running (hence the WIP).
This idea was discussed in private with @SylvainCorlay, putting the PR out as a potential fix for https://github.com/spyder-ide/spyder/issues/16183

✨ avoid using nest_asyncio

---

packages/vaex-core/vaex/dataframe.py
tests/export_test.py

This fixes #1063 
`df.export_csv(..)` was crashing if `header`, `mode`, or `index` where specified by the user. 
This PR fixes that

fix double kwargs issue in export_csv

---

packages/vaex-core/vaex/functions.py
packages/vaex-ml/vaex/ml/transformations.py
tests/dot_product_test.py
tests/ml/pipeline_test.py

This PR improves the dot_product. Before there was a limitation of the size of the vectors one can use to calculate a dot product. Now that limitation is lifted. So things like PCA, and Incremental PCA can be used with hundreds of dimensions. 
The dot product is made available more generally in `df.func.dot_product`.

Better dot_product

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/settings.py
packages/vaex-core/vaex/utils.py
tests/repr_test.py

This PR adds the possibility for the user to control how many columns are visible when printing/displaying the dataframe. Prior to this PR, all column were always shown, resulting in show displaying when a dataframe contains thousands of columns. 
The default is now 50 columns. One can modify this via
```python
vaex.settings.display.max_columns =  20 # for example
```
There is an equivalent setting for the max number of rows
```
vaex.settings.display.max_rows =  20 # for example
```
Checklist:
Example:

Feat: add display settings

---

packages/vaex-core/vaex/functions.py
tests/strings_test.py

Addresses the issue raised in #1697
Checklist:

fix(core): fix str.rsplit() when an explicit split pattern is specified

---

packages/vaex-core/vaex/dataframe.py

Explicitly only allow single boolean value sorting in `sort` function.
In numpy you can pass in a list to sort and the sort function will sort by each column independently based on the list. Since vaex does not support this, it should be explicit, to avoid unexpected results by the user. 
https://github.com/vaexio/vaex/issues/1631
https://github.com/vaexio/vaex/issues/815

Explicit `ascending` check in `sort` function

---

packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/expresso.py
packages/vaex-core/vaex/metal.py
tests/jit_test.py

Proof of concept for jitting using Metal. Unfortunately, this does not work that great. We can't schedule multiple compute kernels multithreaded, it seems to share some memory/state, because the results are garbled up without the lock in `metal.py`. Disabling ths lock gives speedups of `>2x`, on a 2018 MacBook 15" with Radeon Pro 560 4GB. With the lock the performance is the same as on my CPU.
Requires https://github.com/wtnb75/runmetal/
`pip install git+https://github.com/wtnb75/runmetal/` should do it.
A way out could be to do an MetalExecutor, meaning we take control of the whole execution part, single threaded, and execute all the code on the GPU, but that requires a lot more work.
Putting this out there in case someone finds this interesting, or has ideas how to avoid that lock. …

feat: support jitting using OSX Metal

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/file/s3fs.py

Fixes issue #1714 .
Changes 
1. During recursive call of vaex.open , fs and fs_options augments passed.
2. Added new key scheme for fs_options. If not passed , it will default to https.

Fixing vaex.open for multipart parquet/arrow files

---

packages/vaex-core/vaex/functions.py
tests/astype_test.py

Assuming `x` is integer, this now will work: `df.x.astype('timedelta64[s]')`
Requested by: https://github.com/vaexio/vaex/discussions/1740
Checklist:

Allow casting integers to timedelta64 type

---

packages/vaex-viz/vaex/viz/__init__.py

`df.x.viz.histogram(..)` was not propagating the `**kwargs` to the "parent" `df.viz.histogram(..)` method. Now it does.

fix: histogram method on expression to propagate kwargs

---

packages/vaex-core/vaex/array_types.py
tests/evaluate_test.py

Currently `df.x.evaluate(selection='...')` fails the underlying data of `x` is in arrow. 
This PR fixes that and adds a more stable test.

Fix: Evaluate with selections

---

ci/conda-env.yml

Remote dataframe seems to not do the progress/cancel part on these two platforms, only difference seems unicorn 0.16, although that does work on windows/3.7.

ci: avoid uvicorn 0.16 for windows/3.8,3.9

---

packages/vaex-core/vaex/dataframe.py
tests/evaluate_test.py

e.g. a columns having names like '#' or 'with space' would trigger an unneeded pass over the data.

✨ avoid evaluating materialized columns that are non-identifiers

---

packages/vaex-core/vaex/arrow/dataset.py
tests/arrow/io_test.py

Pass along schema explicitly so that empty files can be opened

Handle empty arrow files

---

ci/conda-env.yml
packages/vaex-core/setup.py
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/delayed.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/misc/progressbar.py
packages/vaex-core/vaex/progress.py
packages/vaex-core/vaex/settings.py
packages/vaex-core/vaex/tasks.py
packages/vaex-core/vaex/utils.py
packages/vaex-hdf5/vaex/hdf5/writer.py
setup.py
tests/progress_test.py

We now also report if it comes from cache or when an error occured.
Also moved out of utils.py to progress.py

🔨 cleanup of progress bar and tree

---

packages/vaex-hdf5/vaex/hdf5/dataset.py
packages/vaex-hdf5/vaex/hdf5/writer.py
tests/export_test.py

We add in all occurances of `h5py.require_dataset` the parameter `track_times=False`. With this change, the file generated by exporting to hdf5 will always have the same hash.

Make hdf5 files always generate same file

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/datatype.py
tests/unique_test.py

This PR enables the `unique` method to be valid for expressions of type `datetime64` and `timedelta64`

Enable unique for datetime64 and timedelta64 expressions

---

packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/multithreading.py
packages/vaex-server/vaex/server/executor.py

We use generators now, so the 'top level'
execute_async can still do task switching while sharing the same
code with the sync version.
The remote executor will prefer to use the async version, and will
use nest asyncio when a sync call is done.

✨ do not use asyncio for the sync execute path

---

packages/vaex-core/vaex/execution.py
packages/vaex-server/vaex/server/fastapi.py
tests/execution_test.py

Now multiple tasks can call the executor, which allows us to await
the executor and tasks, which make it work better with for instance
FastAPI.

✨ executor is async safe, similar to thread safe

---

packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/promise.py
tests/execution_test.py

This allows us to write async code like this:
```
async def means():
count, sum = await asyncio.gather(df.x.count(delay=True), df.x.sum(delay=True))
mean = await df.x.mean(delay=True)
return sum / count, mean
```
However, vaex does not automatically start executing tasks (only when
explicitly asked for).
Even worse, the executor might stop the task executing loop, before
new tasks are added (here the call to mean() might happen too late)
Within this new context manager, the executor will automatically get called
```
async with df.executor.auto_execute():
mean1, mean2 = await means()
```

✨ auto execute task context manager when awaiting task or promise

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/dataset.py
tests/arrow/io_test.py

What do you think of `df.schema_arrow`, is it time for an `arrow` accessor, so we have `df.arrow.schema()` ?

🐛 support empty parquet and arrow files

---

packages/vaex-core/vaex/functions.py
tests/datetime_test.py

When loading feather files with pyarrow 6.0.1, dt methods fail because the underlying arrays are chunked. This change modifies the test to handle chunked arrays.

handle chunked arrays in _pandas_dt_fix

---

packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/multithreading.py
tests/progress_test.py

`py.test tests/progress_test.py -k test_cancel_huge` for instance cancels much quicker, because it does not have to wait for the blocking yield in the thread pool.

✨ execute_async block less, doing true await on the thread pool

---

.github/workflows/pythonpackage.yml
packages/vaex-core/vaex/execution.py
packages/vaex-server/vaex/server/fastapi.py
packages/vaex-server/vaex/server/tornado_server.py
packages/vaex-server/vaex/server/websocket.py
tests/execution_test.py
tests/from_pandas_test.py

Given CI runs much better, and we still distributed py36 wheels, lets see if we can get CI restored again.

ci: restore python 3.6

---

packages/vaex-core/src/hash.hpp
packages/vaex-core/src/hash_object.cpp
packages/vaex-core/src/hash_primitives.cpp
packages/vaex-core/src/hash_primitives.hpp
packages/vaex-core/src/hash_string.cpp
packages/vaex-core/src/hash_string.hpp
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/docstrings.py
packages/vaex-core/vaex/encoding.py
packages/vaex-core/vaex/execution.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/hash.py
packages/vaex-core/vaex/json.py
packages/vaex-core/vaex/tasks.py
tests/execution_test.py
tests/hashmap_unique_test.py
tests/internal/hash_test.py
tests/progress_test.py
tests/unique_test.py

This also includes a refactor of what we previously called 'set'
or 'ordered_set'.
This is now renamed to HashMapUnique, which describes what it does:
It maps keys to unique integers between [0, len(map)-1] using a
hashmap.
To support limit with limit_raise=False, we need tasks to stop early
but still return a value.
The default 'limit_raise=True' is consistent with groupby's row_limit
and is much safer behaviour.

✨ limit and limit_raise for unique and nunique

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/datatype.py
packages/vaex-core/vaex/expression.py
packages/vaex-core/vaex/functions.py
packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/hash.py
tests/category_test.py
tests/shape_test.py

Before the ordinal encode would materialize the 'index' or 'codes'
numerical array. This is fine if you care about performance, but
if you want to do this on large dataframes, with the purpose of
exporting, you'd want to do this lazily.

✨ Lazy ordinal encode

---

docs/source/api.rst
packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/logging.py
packages/vaex-core/vaex/settings.py

We also use Rich to have beautiful default logging to console. This can be disabled using the settings.

feat: configure logging using settings system

---

packages/vaex-core/vaex/groupby.py
tests/groupby_test.py

Otherwise variable names would be df['#'] instead of '#'

🐛 use label instead of expression for non-ident column names in binby

---

.github/workflows/pythonpackage.yml
ci/actions/windll/action.yml
ci/conda-env.yml
packages/vaex-core/vaex/column.py
packages/vaex-core/vaex/functions.py
tests/astype_test.py

As discussed here: https://github.com/vaexio/vaex/issues/1907#issuecomment-1039049309
Checklist:

Improve casting of strings to datetime

---

packages/vaex-core/vaex/dataframe.py
tests/dtypes_test.py

This is quite an exotic bug, discovered by https://github.com/vaexio/vaex/discussions/1933.
Sometimes doing `df.y.dt.strftime('%Y')` results in a dtype of `null` (?). However, this only happens if the dataframe contains another column, say `x` of dtype `string` that has at least two missing values, of which one _has to be in the first position_.  If one does `dropna()` in that column `x`, the result of doing `strftime` on `y` gives weird dtype (see unit test for better explanation). 
See https://github.com/vaexio/vaex/discussions/1933 for a temporary workaround.
Checklist

🐛 apply with filtered data could give wrong dtypes

---

packages/vaex-core/src/agg_first.cpp
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/utils.py
tests/first_test.py

Also, if no order argument is given, the row number is used.
After #1847 it's easier to add new aggregators, so I took the time to fix first, and add last.
Replaces https://github.com/vaexio/vaex/pull/1834
Closes https://github.com/vaexio/vaex/issues/1378
cc @yohplala
TODO:
1. [ ] improve docstrings explaining this
2. [ ] test and implement selections, test missing/masked data
Either @JovanVeljanoski or @yohplala would you like to work on these last two points? If this shows up issues (I know selections are not implemented), I can fix those.

✨ last aggregor, and first and last now can have mixed types

---

benchmarks/sort.py
packages/vaex-core/vaex/dataframe.py
tests/sort_test.py

This improves the sorting method:
- uses pyarrow under the hood
- allow for sorting of strings
- allow the "ascending" order to be specified for each key. 
Example:
```python
import vaex
df = vaex.datasets.titanic()
df_sorted = df.sort(by=['age', 'fare', 'name'], ascending=[True, False, True])
```
This also solves: https://github.com/vaexio/vaex/pull/1211
Closes: https://github.com/vaexio/vaex/issues/1208 https://github.com/vaexio/vaex/issues/815

improv(core): Improve `df.sort`

---

.github/workflows/pythonpackage.yml

setup-gcloud will be updating the branch name from master to main in a future release. Even though GitHub will establish redirects, this will break any GitHub Actions workflows that pin to master. This PR updates your GitHub Actions workflows to pin to v0, which is the recommended best practice.

Pin setup-gcloud to v0 instead of master

---

packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/expression.py
tests/agg_test.py

Notes:
- This PR has been branched off https://github.com/vaexio/vaex/pull/1848 and thus requires that branch to be merged first since we are using the refactoring done there
- Closes https://github.com/vaexio/vaex/issues/1215
Checklist:

Feat: add `skew` and `kurtosis` aggregators.

---

packages/vaex-core/setup.py

Again breakage, followup of https://github.com/vaexio/vaex/pull/1873
I think this is taking too much time, and we should drop this, what do you think @JovanVeljanoski ?

fix: avoid dask 2022.4.0

---

packages/vaex-core/vaex/join.py
tests/join_test.py

Probably introduced in #480
Fixes #1127

fix: join would fail if the rhs had no columns besides the join one

---

packages/vaex-core/vaex/dataset.py
tests/concat_test.py
tests/export_test.py

test(core): hdf5 export fails for concat df with missing columns

---

packages/vaex-core/vaex/dataframe.py
tests/column_names_test.py

As it would lead to recursion error.
Fixes #1992

🐛 allow col as column name

---

packages/vaex-core/vaex/groupby.py
tests/agg_test.py

We assumed the data to be numpy data.
This didn't affect the dense binners where we did not have to post-filter the arrays.
cc @Ben-Epstein

🐛 when aggregation leads to arrow data, non-dense binners fail

---

packages/vaex-core/vaex/groupby.py
tests/agg_test.py

🐛 multi-d sparse groupby would fail for arrow data (e.g. list agg)

---

packages/vaex-core/vaex/dataframe.py
tests/export_test.py

We tried to cast to small strings, but did not do this for the schema.
Fixes #2021

🐛 exporting arrow with large_string would result in schema conflict

---

packages/vaex-core/vaex/expresso.py
tests/expresso_test.py

🐛 expression engine did not roundtrip dict correctly, missing ,

---

packages/vaex-core/vaex/dataframe.py

In some unit tests we discovered that `vaex` is referencing the old `numpy.float` type rather than `numpy.float64` like similar methods. This PR simples changes `numpy.float -> numpy.float64`, which should prevent future errors and silence numpy warnings.

Changed deprecated numpy.float to numpy.float64

---

docs/source/example_advanced_plotting.ipynb
docs/source/example_ml_iris.ipynb
docs/source/example_ml_titanic.ipynb
docs/source/getting_data_in_vaex.rst
docs/source/tutorial.ipynb
docs/source/tutorial_ml.ipynb
packages/vaex-core/vaex/dataset_misc.py
packages/vaex-core/vaex/legacy.py
packages/vaex-core/vaex/test/plot.py
packages/vaex-jupyter/vaex/jupyter/ipympl.py
packages/vaex-ui/vaex/ui/layers.py
packages/vaex-ui/vaex/ui/template_matplotlib.py
packages/vaex-ui/vaex/ui/templates.py
packages/vaex-ui/vaex/ui/volumerendering.py
packages/vaex-viz/vaex/viz/__init__.py
packages/vaex-viz/vaex/viz/contour.py
packages/vaex-viz/vaex/viz/mpl.py
packages/vaex-viz/vaex/viz/tensor.py
packages/vaex-viz/vaex/viz/vector.py

Replaced pylab with matplotlib.pyplot since the use of pylab is [discouraged](https://matplotlib.org/stable/api/index.html?highlight=pylab#module-pylab) by matplotlib.

Remove pylab

---

packages/vaex-core/vaex/dataframe.py
tests/category_test.py

fix: ordinal_encode with values which extra entries gave wrong results

---

packages/vaex-hdf5/vaex/hdf5/writer.py

Otherwise the buffers of the numpy arrays are still being used.
Fixes #2062

🐛 hdf5: do not keep a reference to numpy arrays on closing an hdf5 file

---

.github/workflows/pythonpackage.yml
packages/vaex-core/vaex/groupby.py
tests/groupby_test.py

Which could lead to wrong groupby results.
Fixes: #2048

🐛 wrong order of casting and subtracting offset cause overflow

---

ci/04-run-test-suite.sh
packages/vaex-core/vaex/agg.py
packages/vaex-core/vaex/array_types.py
packages/vaex-core/vaex/groupby.py
tests/groupby_test.py

This PR add/proposes a feature requested in https://github.com/vaexio/vaex/issues/1998
The feature can be best described with an example:
```python
import vaex
df = vaex.datasets.titanic()
res = df.groupby('pclass').describe(['age', df.sex])
print(res)
0         1          284              39     39.1599    14.5224     0.9167         80          323               0
1         2          261              16     29.5067    13.6125     0.6667         70          277               0
2         3          501             208     24.8164    11.9463     0.1667         74          709               0
```
This is a convenience method, but I think it makes sense to add.

Feat: add `describe` method to `groupby`

---

ci/conda-env.yml
packages/vaex-core/src/hash_primitives.hpp
packages/vaex-core/src/hash_string.hpp
tests/internal/hash_test.py
tests/join_test.py

Fixes #2077
The reason this happened sporadically, is that in the C++
code nan_value and null_value were not initialized in the ctor,
but were assumed to be intialized later on. However, since the
hashmap itself never saw the nulls or nans, this did not happen.

fix: join failed when the lhs dataframe had nan/null and the rhs not

---

ci/conda-env.yml
packages/vaex-ml/SCIKIT_LEARN_LICENSE.txt
packages/vaex-ml/vaex/ml/metrics.py
tests/ml/metrics_test.py
tests/server/rest_test.py

At the request of @Ben-Epstein , this is an attempt to make (most) metrics to support the `selections`  argument, in the same style as in various other vaex methods. 
To do:

feat(ml): Enable most metrics to support selections

---

packages/vaex-core/vaex/utils.py

For some reason we used $VAEX_PATH_HOME, while documented it as $VAEX_HOME
It should have been $VAEX_HOME. For backward compatibility we still
use $VAEX_PATH_HOME if is is set.
cc @eff-kay

fix: correct $VAEX_PATH_HOME -> $VAEX_PATH

---

packages/vaex-core/vaex/dataframe.py
tests/dropna_test.py

Fixes https://github.com/vaexio/vaex/issues/2084
I just added tests for dropna(), because I thought the verbosity wouldn't be worth it to add tests for dropinf, etc. But let me know what you think.
I also thought about putting the if/else check in _filter_all outside of the loop, to save a bit of overhead, but I figured that looping through even ~1000 columns would still be overshadowed by the actual going through the data.

FEAT: Add how="any","all" to df.dropna, dropinf, etc

---

ci/conda-env.yml
packages/vaex-core/vaex/dataframe.py
tests/data/badname.csv
tests/export_test.py

Fixes https://github.com/vaexio/vaex/issues/2057

Fix: Export csv with protected column names from arrow data structures

---

tests/dataframe_protocol_test.py

#2122 ended up fixing a somewhat miscellaneous bug, which this PR adds a test for to prevent regressions. The bug in question was due to arrow arrays being passed around to `_VaexBuffer`, which isn't supported, where the fix ended up converting arrow arrays internally before initialising `_VaexBuffer`.

Regression test for interchanging categorical columns

---

packages/vaex-core/src/hash_string.hpp
tests/value_counts_test.py

Closes https://github.com/vaexio/vaex/issues/2146

Fix: value counts for high cardinality strings

---

packages/vaex-core/vaex/dataframe.py
tests/column_names_test.py

Now we can query column names by data type: 
```python 
import vaex
df = vaex.datasets.titanic()
df.get_column_names(dtypes=[float])
```
Several attempts at this have been done at the past. This is my latest proposal and I think it works quite well. 
Closes:
- https://github.com/vaexio/vaex/issues/240
- https://github.com/vaexio/vaex/pull/251
- https://github.com/vaexio/vaex/pull/1766

feature: `get_column_names` accepts a dtypes argument

---

packages/vaex-core/vaex/groupby.py
packages/vaex-core/vaex/utils.py
tests/groupby_test.py
tests/utils_test.py

This fixes https://github.com/vaexio/vaex/issues/2136
Base on the discussion: https://github.com/vaexio/vaex/discussions/2131

Fix: groupby on type int sometimes confuses dtypes

---

packages/vaex-core/vaex/cache.py
tests/fingerprint_test.py

This led to a lot of error:
"You have passed in an object for which we cannot determine a fingerprint"

fix: uuid4 function was not always restored properly

---

packages/vaex-core/vaex/dataframe.py
tests/extract_test.py

This caused errors like:
"NameError: name '__filter__' is not defined"
This happened before we checked in we had a filter, and then removed
the filter in a non-atomic way.

fix: df.extract() was not thread safe

---

.github/workflows/pythonpackage.yml

We want to run the notebooks in CI on every python version save for 3.6

CI: Do not run the notebooks on p36

---

packages/vaex-viz/vaex/viz/mpl.py

correctly place the colorbar for matplotlib 3.6.0

Fix for the vaex-viz CI issue due to the latest matplotlib (3.6.0)

---

packages/vaex-core/vaex/dataframe_protocol.py
tests/dataframe_protocol_test.py

This will align the implementation with those in other libraries, xref https://github.com/data-apis/dataframe-api/issues/80.
Cc @maartenbreddels, @honno

Add a `__dataframe__` method to `_VaexDataFrame`

---

packages/vaex-astro/vaex/astro/legacy.py

Small fix in add_virtual_columns_eq2gal calling the eq2ecl function instead of the eq2gal function. This is an old bug (see #989 https://github.com/vaexio/vaex/issues/989) with a very simple fix.

Fix Typo in eq2gal

---

packages/vaex-core/vaex/csv.py
tests/csv_test.py

We have to recreate the object, but were passing it it's own function as ctor arguments.

fix: convert options for lazy from_csv_arrow did not work

---

packages/vaex-core/vaex/arrow/dataset.py
tests/from_test.py

For instance when reading multiple arrow/feather files.
Fixes #2219

fix: support arrow datasets containing multiple fragment without row_groups

---

packages/vaex-core/vaex/dataframe.py
tests/materialize_test.py

`df.materialize()` expects a list of columns / expressions. This PR allows for users to put in a single column/expression. 
Raised by https://github.com/vaexio/vaex/issues/2247

Fix: allow single columns or expressions in materialize

---

ci/04-run-test-suite.sh
packages/vaex-core/vaex/cpu.py
packages/vaex-core/vaex/dataset.py
packages/vaex-hdf5/vaex/hdf5/dataset.py
packages/vaex-hdf5/vaex/hdf5/writer.py
tests/concat_test.py
tests/export_test.py

When we have pyarrow numeric data with missing values, the missing data are not correctly exported to hdf5.

Fix: export to hdf5 when there are numeric missing values

---

packages/vaex-core/vaex/cpu.py
tests/count_test.py
tests/viz_test.py

This issue could in partly due to `count` something being buggy when handling arrow data that has missing values. Not sure tho, but there are tests implemented that cover these things in both sides for safety (asserting the histogram output and the `count` output). 
_Workaround:_
If somebody is struggling with this issue, there is a simple workaround. Say column `x` is arrow column with missing values. All you need to do is:
```python
df['x'] = df.x.as_numpy()
```
and everything should work as expected.
_Checklist:_

Fix: histogram sometimes does not obey selections

---

packages/vaex-core/vaex/expression.py
tests/filter_test.py

Allow to create a filter via a `pyarrow.StringScalar`. Raised by: https://github.com/vaexio/vaex/issues/2242

Fix: filtering with an arrow string scalar

---

packages/vaex-core/vaex/dataframe.py
packages/vaex-core/vaex/selections.py
tests/column_names_test.py

Credit to Hotaru which discovered this problem and alerted us via Slack. 
If a name has a math symbol (like a minus sigh) it sometimes causes problems.  This PR exposes the problem and addresses that.

Fix: names with math symbols should work consistently

---

packages/vaex-core/vaex/dataframe.py
tests/sort_test.py

Addresses https://github.com/vaexio/vaex/issues/2287
@maartenbreddels I wrapped this up in `try/expect` block as to now check for length every time a df is sorted. If you think this should be done the other way around (i.e. first check length) then try to sort, lemme know!
Thanks to @NickCrews for bringing this up.

Fix: sorting of an empty df returns an empty df with a warning

---

packages/vaex-core/vaex/dataframe.py
tests/extract_test.py

I think this is a better way to handle extracting an empty dataframe than https://github.com/vaexio/vaex/pull/2267
relates to https://github.com/vaexio/vaex/issues/2232

Better handle empty extract

---

packages/vaex-core/vaex/__init__.py
packages/vaex-core/vaex/dataset.py
packages/vaex-core/vaex/file/__init__.py
packages/vaex-core/vaex/memory.py
packages/vaex-core/vaex/tasks.py
packages/vaex-core/vaex/utils.py

This is a hot fix for the IO read issues caused by using the legacy pkg_resources.iter_entry_points
legacy `pkg_resources.iter_entry_points` is replaced with `importlib.metadata.entry_points`
```python
try:
if sys.version_info[:2] >= (3, 10):
from importlib.metadata import entry_points
else:
from importlib_metadata import entry_points
except ImportError:
import pkg_resources
entry_points = pkg_resources.iter_entry_points
```

Remove pkg_resources from direct imports

---

packages/vaex-hdf5/vaex/hdf5/writer.py
tests/export_test.py

This fixes some issues we've encountered with exporting some type of data to hdf5. The unit-tests have been scaled the reproduce the issues via minimal data, but the same issues are encountered with the `default_chunk_size` on larger datasets. 
I suspect this is due to a combination of `chunk_size` and amount of missing/masked values in a particular chunk.
I do not know the exact origin of the errors at this point, so the tests have rather generic names.
Each of the unit-tests raises a different error, which is why I created separate tests rather than one in which the amount of  data is varied.
Exporting the same data under the same conditions (i.e. `chunk_size`) to arrow or parquet format works just fine. 
Checklist:

Fix: reliable export hdf5 with small chunks size

---

.github/workflows/pythonpackage.yml
.github/workflows/wheel.yml

leftover from #2331, don't know why setup-graphviz started failing for macos-13 on master between the time of last commit in the PR and the time of merge. probably github team changed something in the runner image again...

Fix pythonpackage.yml failing on macos-13

---

.github/workflows/wheel.yml
packages/vaex-core/pyproject.toml
packages/vaex-core/setup.py
tests/fingerprint_test.py

Supersedes https://github.com/vaexio/vaex/pull/2433, see also https://github.com/scipy/oldest-supported-numpy/pull/86
on master there is only one failing wheel build: https://github.com/vaexio/vaex/actions/runs/10835977160/job/30068700570
due to oldest-supported-numpy selecting a version of numpy for which no wheels are available. building numpy from source under QEMU takes forever, so we're hitting the builtin github actions 6 hour timeout (which can't be increased)

fix: avoid cp39-musllinux_aarch64 timeout

---

packages/vaex-core/setup.py
packages/vaex-core/src/hash_primitives.hpp
packages/vaex-core/src/hash_string.hpp

This is only to check if we now catch the error in CI, the fix will come in a later commit.
See https://github.com/vaexio/vaex/issues/2439

fix: don't release the gil to early

---

.github/workflows/wheel.yml
packages/vaex-core/vaex/core/_version.py
packages/vaex/setup.py

cibuildwheel now creates wheels with Metadata 2.4, whereas current pypa/gh-action-pypi-publish only allows up until 2.3

Bump pypa/gh-action-pypi-publish
